//
//  ADASCruiseControl.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class ADASCruiseControl: Object, ObjectSchema {

    /// Indicates if cruise control system incurred and error condition. True = Error. False = NoError.
    var error = Field<Bool?, NoArguments>("error")

    /// Indicates if cruise control system is enabled. True = Enabled. False = Disabled.
    var isActive = Field<Bool?, NoArguments>("isActive")

    /// Set cruise control speed in kilometers per hour
    var speedSet = Field<Float?, NoArguments>("speedSet")

    public required init() { }
}