//
//  BodyWindshield.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class BodyWindshield: Object, ObjectSchema {

    var front = Field<BodyWindshieldFront?, NoArguments>("front")

    var rear = Field<BodyWindshieldRear?, NoArguments>("rear")

    public required init() { }
}