//
//  BodyHorn.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class BodyHorn: Object, ObjectSchema {

    /// Horn active or inactive. True = Active. False = Inactive.
    var isActive = Field<Bool?, NoArguments>("isActive")

    public required init() { }
}