//
//  CabinInfotainmentHMIFuelEconomyUnits.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum CabinInfotainmentHMIFuelEconomyUnits: String, Enum {

    case mpgUk = "mpg_UK"

    case mpgUs = "mpg_US"

    case mpl = "mpl"

    case kmL = "km_l"

    case l100Km = "l_100km"
}