//
//  CabinSeatRow4Pos2SwitchSideBolster.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class CabinSeatRow4Pos2SwitchSideBolster: Object, ObjectSchema {

    /// Lumbar deflation switch engaged
    var deflate = Field<Bool?, NoArguments>("deflate")

    /// Lumbar inflation switch engaged
    var inflate = Field<Bool?, NoArguments>("inflate")

    public required init() { }
}