//
//  CabinInfotainmentHMITemperatureUnit.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum CabinInfotainmentHMITemperatureUnit: String, Enum {

    case C = "C"

    case F = "F"
}