//
//  Cabin.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class Cabin: Object, ObjectSchema {

    var convertible = Field<CabinConvertible?, NoArguments>("convertible")

    var door = Field<CabinDoor?, NoArguments>("door")

    var hvac = Field<CabinHVAC?, NoArguments>("hvac")

    var infotainment = Field<CabinInfotainment?, NoArguments>("infotainment")

    var lights = Field<CabinLights?, NoArguments>("lights")

    var rearShade = Field<CabinRearShade?, NoArguments>("rearShade")

    var rearviewMirror = Field<CabinRearviewMirror?, NoArguments>("rearviewMirror")

    var seat = Field<CabinSeat?, NoArguments>("seat")

    var steeringWheel = Field<CabinSteeringWheel?, NoArguments>("steeringWheel")

    var sunroof = Field<CabinSunroof?, NoArguments>("sunroof")

    public required init() { }
}