//
//  CabinInfotainmentHMIDistanceUnit.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum CabinInfotainmentHMIDistanceUnit: String, Enum {

    case mi = "mi"

    case km = "km"
}