//
//  CabinInfotainmentHMIEVEconomyUnits.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum CabinInfotainmentHMIEVEconomyUnits: String, Enum {

    case miKwh = "mi_kWh"

    case kmKwh = "km_kWh"

    case kWh100Mi = "kWh_100mi"

    case kWh100Km = "kWh_100km"

    case WhMi = "Wh_mi"

    case WhKm = "Wh_km"
}