//
//  CabinInfotainmentHMI.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class CabinInfotainmentHMI: Object, ObjectSchema {

    /// ISO 639-1 standard language code for the current HMI
    var currentLanguage = Field<String?, NoArguments>("currentLanguage")

    /// Date format used in the current HMI
    var dateFormat = Field<CabinInfotainmentHMIDateFormat?, NoArguments>("dateFormat")

    /// Current display theme
    var dayNightMode = Field<CabinInfotainmentHMIDayNightMode?, NoArguments>("dayNightMode")

    /// Distance unit used in the current HMI
    var distanceUnit = Field<CabinInfotainmentHMIDistanceUnit?, NoArguments>("distanceUnit")

    /// EV fuel economy unit used in the current HMI
    var evEconomyUnits = Field<CabinInfotainmentHMIEVEconomyUnits?, NoArguments>("evEconomyUnits")

    /// Fuel economy unit used in the current HMI
    var fuelEconomyUnits = Field<CabinInfotainmentHMIFuelEconomyUnits?, NoArguments>("fuelEconomyUnits")

    /// Temperature unit used in the current HMI
    var temperatureUnit = Field<CabinInfotainmentHMITemperatureUnit?, NoArguments>("temperatureUnit")

    /// Time format used in the current HMI
    var timeFormat = Field<CabinInfotainmentHMITimeFormat?, NoArguments>("timeFormat")

    public required init() { }
}