//
//  CabinLightsRow2Left.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class CabinLightsRow2Left: Object, ObjectSchema {

    /// Is passenger light on
    var isPassengerOn = Field<Bool?, NoArguments>("isPassengerOn")

    public required init() { }
}