//
//  CabinInfotainmentMedia.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class CabinInfotainmentMedia: Object, ObjectSchema {

    /// Tells if the media was
    var action = Field<CabinInfotainmentMediaAction?, NoArguments>("action")

    /// URI of suggested media that was declined
    var declinedURI = Field<String?, NoArguments>("declinedURI")

    var played = Field<CabinInfotainmentMediaPlayed?, NoArguments>("played")

    /// URI of suggested media that was selected
    var selectedURI = Field<String?, NoArguments>("selectedURI")

    /// Current Media Volume
    var volume = Field<Int?, NoArguments>("volume")

    public required init() { }
}