//
//  CabinSeatRow4.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class CabinSeatRow4: Object, ObjectSchema {

    var pos1 = Field<CabinSeatRow4Pos1?, NoArguments>("pos1")

    var pos2 = Field<CabinSeatRow4Pos2?, NoArguments>("pos2")

    var pos3 = Field<CabinSeatRow4Pos3?, NoArguments>("pos3")

    var pos4 = Field<CabinSeatRow4Pos4?, NoArguments>("pos4")

    var pos5 = Field<CabinSeatRow4Pos5?, NoArguments>("pos5")

    public required init() { }
}