//
//  ChassisAxleRow2WheelRightTire.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class ChassisAxleRow2WheelRightTire: Object, ObjectSchema {

    /// Tire pressure in kilo-Pascal
    var pressure = Field<Int?, NoArguments>("pressure")

    /// Tire Pressure Status. True = Low tire pressure. False = Good tire pressure.
    var pressureLow = Field<Bool?, NoArguments>("pressureLow")

    /// Tire temperature in Celsius.
    var temperature = Field<Float?, NoArguments>("temperature")

    public required init() { }
}