//
//  DrivetrainTransmissionDriveType.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum DrivetrainTransmissionDriveType: String, Enum {

    case unknown = "unknown"

    case forwardWheelDrive = "forward_wheel_drive"

    case rearWheelDrive = "rear_wheel_drive"

    case allWheelDrive = "all_wheel_drive"
}