//
//  OBDO2AltBank1Sensor1.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class OBDO2AltBank1Sensor1: Object, ObjectSchema {

    /// Dummy description
    var dummyField = Field<String?, NoArguments>("dummyField")

    public required init() { }
}