//
//  OBDO2WRSensor1.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class OBDO2WRSensor1: Object, ObjectSchema {

    /// PID 34 - Lambda current for wide range/band oxygen sensor 1
    var current = Field<Float?, NoArguments>("current")

    /// PID 24 - Lambda voltage for wide range/band oxygen sensor 1
    var voltage = Field<Float?, NoArguments>("voltage")

    public required init() { }
}