import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Body_Mirrors {
     left: Vehicle_Body_Mirrors_Left
     right: Vehicle_Body_Mirrors_Right
   }
*/

final class Vehicle_Body_Mirrors: Object, ObjectSchema {

    var left = Field<Vehicle_Body_Mirrors_Left?, NoArguments>("left")

    var right = Field<Vehicle_Body_Mirrors_Right?, NoArguments>("right")

}


public class Body_Mirrors: Model {

    typealias PartialType = Vehicle_Body_Mirrors

    public let left: Body_Mirrors_Left?
    public let right: Body_Mirrors_Right?

    required init?(partial: Partial<PartialType?>) {
        left = Body_Mirrors_Left(partial: partial.left)
        right = Body_Mirrors_Right(partial: partial.right)
    }
}
