import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    enum Vehicle_Drivetrain_Transmission_GearChangeMode_Enum {
     manual
     automatic
   }
*/

public enum Vehicle_Drivetrain_Transmission_GearChangeMode_Enum: String, Enum {
   case manual = "manual"
   case automatic = "automatic"
}

public typealias Drivetrain_Transmission_GearChangeMode_Enum = Vehicle_Drivetrain_Transmission_GearChangeMode_Enum
