import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Drivetrain_FuelCell {
     """
     Dummy description
     """
     dummyField: String
   }
*/

final class Vehicle_Drivetrain_FuelCell: Object, ObjectSchema {

    /**
    Dummy description
    */
    var dummyField = Field<String?, NoArguments>("dummyField")

}


public class Drivetrain_FuelCell: Model {

    typealias PartialType = Vehicle_Drivetrain_FuelCell

    public let dummyField: String?

    required init?(partial: Partial<PartialType?>) {
        dummyField = partial.dummyField ?? nil
    }
}
