import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Chassis_Axle_Row2 {
     """
     Diameter of tires, in inches, as per ETRO / TRA standard.
     """
     tireDiameter: Int
     """
     Width of tires, in inches, as per ETRO / TRA standard.
     """
     tireWidth: Int
     wheel: Vehicle_Chassis_Axle_Row2_Wheel
     """
     Diameter of wheels (without tires), in inches, as per ETRO / TRA standard.
     """
     wheelDiameter: Int
     """
     Width of wheels (without tires), in inches, as per ETRO / TRA standard.
     """
     wheelWidth: Int
   }
*/

final class Vehicle_Chassis_Axle_Row2: Object, ObjectSchema {

    /**
    Diameter of tires, in inches, as per ETRO / TRA standard.
    */
    var tireDiameter = Field<Int?, NoArguments>("tireDiameter")

    /**
    Width of tires, in inches, as per ETRO / TRA standard.
    */
    var tireWidth = Field<Int?, NoArguments>("tireWidth")

    var wheel = Field<Vehicle_Chassis_Axle_Row2_Wheel?, NoArguments>("wheel")

    /**
    Diameter of wheels (without tires), in inches, as per ETRO / TRA standard.
    */
    var wheelDiameter = Field<Int?, NoArguments>("wheelDiameter")

    /**
    Width of wheels (without tires), in inches, as per ETRO / TRA standard.
    */
    var wheelWidth = Field<Int?, NoArguments>("wheelWidth")

}


public class Chassis_Axle_Row2: Model {

    typealias PartialType = Vehicle_Chassis_Axle_Row2

    public let tireDiameter: Int?
    public let tireWidth: Int?
    public let wheel: Chassis_Axle_Row2_Wheel?
    public let wheelDiameter: Int?
    public let wheelWidth: Int?

    required init?(partial: Partial<PartialType?>) {
        tireDiameter = partial.tireDiameter ?? nil
        tireWidth = partial.tireWidth ?? nil
        wheel = Chassis_Axle_Row2_Wheel(partial: partial.wheel)
        wheelDiameter = partial.wheelDiameter ?? nil
        wheelWidth = partial.wheelWidth ?? nil
    }
}
