import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    enum Vehicle_Cabin_Convertible_Status_Enum {
     undefined
     closed
     open
     closing
     opening
     stalled
   }
*/

public enum Vehicle_Cabin_Convertible_Status_Enum: String, Enum {
   case undefined = "undefined"
   case closed = "closed"
   case open = "open"
   case closing = "closing"
   case opening = "opening"
   case stalled = "stalled"
}

public typealias Cabin_Convertible_Status_Enum = Vehicle_Cabin_Convertible_Status_Enum
