import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Body_Windshield_Rear {
     heating: Vehicle_Body_Windshield_Rear_Heating
     washerFluid: Vehicle_Body_Windshield_Rear_WasherFluid
     wiping: Vehicle_Body_Windshield_Rear_Wiping
   }
*/

final class Vehicle_Body_Windshield_Rear: Object, ObjectSchema {

    var heating = Field<Vehicle_Body_Windshield_Rear_Heating?, NoArguments>("heating")

    var washerFluid = Field<Vehicle_Body_Windshield_Rear_WasherFluid?, NoArguments>("washerFluid")

    var wiping = Field<Vehicle_Body_Windshield_Rear_Wiping?, NoArguments>("wiping")

}


public class Body_Windshield_Rear: Model {

    typealias PartialType = Vehicle_Body_Windshield_Rear

    public let heating: Body_Windshield_Rear_Heating?
    public let washerFluid: Body_Windshield_Rear_WasherFluid?
    public let wiping: Body_Windshield_Rear_Wiping?

    required init?(partial: Partial<PartialType?>) {
        heating = Body_Windshield_Rear_Heating(partial: partial.heating)
        washerFluid = Body_Windshield_Rear_WasherFluid(partial: partial.washerFluid)
        wiping = Body_Windshield_Rear_Wiping(partial: partial.wiping)
    }
}
