import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_OBD_O2WR_Sensor5 {
     """
     PID 38 - Lambda current for wide range/band oxygen sensor 5
     """
     current: Float
     """
     PID 28 - Lambda voltage for wide range/band oxygen sensor 5
     """
     voltage: Float
   }
*/

final class Vehicle_OBD_O2WR_Sensor5: Object, ObjectSchema {

    /**
    PID 38 - Lambda current for wide range/band oxygen sensor 5
    */
    var current = Field<Float?, NoArguments>("current")

    /**
    PID 28 - Lambda voltage for wide range/band oxygen sensor 5
    */
    var voltage = Field<Float?, NoArguments>("voltage")

}


public class OBD_O2WR_Sensor5: Model {

    typealias PartialType = Vehicle_OBD_O2WR_Sensor5

    public let current: Float?
    public let voltage: Float?

    required init?(partial: Partial<PartialType?>) {
        current = partial.current ?? nil
        voltage = partial.voltage ?? nil
    }
}
