import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Chassis_SteeringWheel {
     """
     Steering wheel angle. Positive = degrees to the left. Negative = degrees to the right.
     """
     angle: Int
     """
     Steering wheel column extension from dashboard. 0 = Closest to dashboard. 100 = Furthest from dashboard.
     """
     extension: Int
     """
     Steering wheel column tilt. 0 = Lowest position. 100 = Highest position.
     """
     tilt: Int
   }
*/

final class Vehicle_Chassis_SteeringWheel: Object, ObjectSchema {

    /**
    Steering wheel angle. Positive = degrees to the left. Negative = degrees to the right.
    */
    var angle = Field<Int?, NoArguments>("angle")

    /**
    Steering wheel column extension from dashboard. 0 = Closest to dashboard. 100 = Furthest from dashboard.
    */
    var `extension` = Field<Int?, NoArguments>("extension")

    /**
    Steering wheel column tilt. 0 = Lowest position. 100 = Highest position.
    */
    var tilt = Field<Int?, NoArguments>("tilt")

}


public class Chassis_SteeringWheel: Model {

    typealias PartialType = Vehicle_Chassis_SteeringWheel

    public let angle: Int?
    public let `extension`: Int?
    public let tilt: Int?

    required init?(partial: Partial<PartialType?>) {
        angle = partial.angle ?? nil
        `extension` = partial.`extension` ?? nil
        tilt = partial.tilt ?? nil
    }
}
