import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_ADAS_ABS {
     """
     Indicates if ABS incurred an error condition. True = Error. False = No Error.
     """
     error: Boolean
     """
     Indicates if ABS is enabled. True = Enabled. False = Disabled.
     """
     isActive: Boolean
     """
     Indicates if ABS is currently regulating brake pressure. True = Engaged. False = Not Engaged.
     """
     isEngaged: Boolean
   }
*/

final class Vehicle_ADAS_ABS: Object, ObjectSchema {

    /**
    Indicates if ABS incurred an error condition. True = Error. False = No Error.
    */
    var error = Field<Bool?, NoArguments>("error")

    /**
    Indicates if ABS is enabled. True = Enabled. False = Disabled.
    */
    var isActive = Field<Bool?, NoArguments>("isActive")

    /**
    Indicates if ABS is currently regulating brake pressure. True = Engaged. False = Not Engaged.
    */
    var isEngaged = Field<Bool?, NoArguments>("isEngaged")

}


public class ADAS_ABS: Model {

    typealias PartialType = Vehicle_ADAS_ABS

    public let error: Bool?
    public let isActive: Bool?
    public let isEngaged: Bool?

    required init?(partial: Partial<PartialType?>) {
        error = partial.error ?? nil
        isActive = partial.isActive ?? nil
        isEngaged = partial.isEngaged ?? nil
    }
}
