import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_OBD_Catalyst_Bank1 {
     """
     PID 3C - Catalyst temperature from bank 1, sensor 1
     """
     temperature1: Float
     """
     PID 3E - Catalyst temperature from bank 1, sensor 2
     """
     temperature2: Float
   }
*/

final class Vehicle_OBD_Catalyst_Bank1: Object, ObjectSchema {

    /**
    PID 3C - Catalyst temperature from bank 1, sensor 1
    */
    var temperature1 = Field<Float?, NoArguments>("temperature1")

    /**
    PID 3E - Catalyst temperature from bank 1, sensor 2
    */
    var temperature2 = Field<Float?, NoArguments>("temperature2")

}


public class OBD_Catalyst_Bank1: Model {

    typealias PartialType = Vehicle_OBD_Catalyst_Bank1

    public let temperature1: Float?
    public let temperature2: Float?

    required init?(partial: Partial<PartialType?>) {
        temperature1 = partial.temperature1 ?? nil
        temperature2 = partial.temperature2 ?? nil
    }
}
