import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    enum Vehicle_Cabin_Infotainment_HMI_EVEconomyUnits_Enum {
     mi_kWh
     km_kWh
     kWh_100mi
     kWh_100km
     Wh_mi
     Wh_km
   }
*/

public enum Vehicle_Cabin_Infotainment_HMI_EVEconomyUnits_Enum: String, Enum {
   case mi_kWh = "mi_kWh"
   case km_kWh = "km_kWh"
   case kWh_100mi = "kWh_100mi"
   case kWh_100km = "kWh_100km"
   case Wh_mi = "Wh_mi"
   case Wh_km = "Wh_km"
}

public typealias Cabin_Infotainment_HMI_EVEconomyUnits_Enum = Vehicle_Cabin_Infotainment_HMI_EVEconomyUnits_Enum
