import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Cabin_Infotainment_HMI {
     """
     ISO 639-1 standard language code for the current HMI
     """
     currentLanguage: String
     """
     Date format used in the current HMI
     """
     dateFormat: Vehicle_Cabin_Infotainment_HMI_DateFormat_Enum
     """
     Current display theme
     """
     dayNightMode: Vehicle_Cabin_Infotainment_HMI_DayNightMode_Enum
     """
     Distance unit used in the current HMI
     """
     distanceUnit: Vehicle_Cabin_Infotainment_HMI_DistanceUnit_Enum
     """
     EV fuel economy unit used in the current HMI
     """
     evEconomyUnits: Vehicle_Cabin_Infotainment_HMI_EVEconomyUnits_Enum
     """
     Fuel economy unit used in the current HMI
     """
     fuelEconomyUnits: Vehicle_Cabin_Infotainment_HMI_FuelEconomyUnits_Enum
     """
     Temperature unit used in the current HMI
     """
     temperatureUnit: Vehicle_Cabin_Infotainment_HMI_TemperatureUnit_Enum
     """
     Time format used in the current HMI
     """
     timeFormat: Vehicle_Cabin_Infotainment_HMI_TimeFormat_Enum
   }
*/

final class Vehicle_Cabin_Infotainment_HMI: Object, ObjectSchema {

    /**
    ISO 639-1 standard language code for the current HMI
    */
    var currentLanguage = Field<String?, NoArguments>("currentLanguage")

    /**
    Date format used in the current HMI
    */
    var dateFormat = Field<Vehicle_Cabin_Infotainment_HMI_DateFormat_Enum?, NoArguments>("dateFormat")

    /**
    Current display theme
    */
    var dayNightMode = Field<Vehicle_Cabin_Infotainment_HMI_DayNightMode_Enum?, NoArguments>("dayNightMode")

    /**
    Distance unit used in the current HMI
    */
    var distanceUnit = Field<Vehicle_Cabin_Infotainment_HMI_DistanceUnit_Enum?, NoArguments>("distanceUnit")

    /**
    EV fuel economy unit used in the current HMI
    */
    var evEconomyUnits = Field<Vehicle_Cabin_Infotainment_HMI_EVEconomyUnits_Enum?, NoArguments>("evEconomyUnits")

    /**
    Fuel economy unit used in the current HMI
    */
    var fuelEconomyUnits = Field<Vehicle_Cabin_Infotainment_HMI_FuelEconomyUnits_Enum?, NoArguments>("fuelEconomyUnits")

    /**
    Temperature unit used in the current HMI
    */
    var temperatureUnit = Field<Vehicle_Cabin_Infotainment_HMI_TemperatureUnit_Enum?, NoArguments>("temperatureUnit")

    /**
    Time format used in the current HMI
    */
    var timeFormat = Field<Vehicle_Cabin_Infotainment_HMI_TimeFormat_Enum?, NoArguments>("timeFormat")

}


public class Cabin_Infotainment_HMI: Model {

    typealias PartialType = Vehicle_Cabin_Infotainment_HMI

    public let currentLanguage: String?
    public let dateFormat: Cabin_Infotainment_HMI_DateFormat_Enum?
    public let dayNightMode: Cabin_Infotainment_HMI_DayNightMode_Enum?
    public let distanceUnit: Cabin_Infotainment_HMI_DistanceUnit_Enum?
    public let evEconomyUnits: Cabin_Infotainment_HMI_EVEconomyUnits_Enum?
    public let fuelEconomyUnits: Cabin_Infotainment_HMI_FuelEconomyUnits_Enum?
    public let temperatureUnit: Cabin_Infotainment_HMI_TemperatureUnit_Enum?
    public let timeFormat: Cabin_Infotainment_HMI_TimeFormat_Enum?

    required init?(partial: Partial<PartialType?>) {
        currentLanguage = partial.currentLanguage ?? nil
        dateFormat = partial.dateFormat ?? nil
        dayNightMode = partial.dayNightMode ?? nil
        distanceUnit = partial.distanceUnit ?? nil
        evEconomyUnits = partial.evEconomyUnits ?? nil
        fuelEconomyUnits = partial.fuelEconomyUnits ?? nil
        temperatureUnit = partial.temperatureUnit ?? nil
        timeFormat = partial.timeFormat ?? nil
    }
}
