import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Chassis_Axle {
     """
     Number of axles on the vehicle
     """
     count: Int
     row1: Vehicle_Chassis_Axle_Row1
     row2: Vehicle_Chassis_Axle_Row2
   }
*/

final class Vehicle_Chassis_Axle: Object, ObjectSchema {

    /**
    Number of axles on the vehicle
    */
    var count = Field<Int?, NoArguments>("count")

    var row1 = Field<Vehicle_Chassis_Axle_Row1?, NoArguments>("row1")

    var row2 = Field<Vehicle_Chassis_Axle_Row2?, NoArguments>("row2")

}


public class Chassis_Axle: Model {

    typealias PartialType = Vehicle_Chassis_Axle

    public let count: Int?
    public let row1: Chassis_Axle_Row1?
    public let row2: Chassis_Axle_Row2?

    required init?(partial: Partial<PartialType?>) {
        count = partial.count ?? nil
        row1 = Chassis_Axle_Row1(partial: partial.row1)
        row2 = Chassis_Axle_Row2(partial: partial.row2)
    }
}
