import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Cabin_Lights_Row4 {
     """
     Is light shared across fourth row on
     """
     isSharedOn: Boolean
     left: Vehicle_Cabin_Lights_Row4_Left
     right: Vehicle_Cabin_Lights_Row4_Right
   }
*/

final class Vehicle_Cabin_Lights_Row4: Object, ObjectSchema {

    /**
    Is light shared across fourth row on
    */
    var isSharedOn = Field<Bool?, NoArguments>("isSharedOn")

    var left = Field<Vehicle_Cabin_Lights_Row4_Left?, NoArguments>("left")

    var right = Field<Vehicle_Cabin_Lights_Row4_Right?, NoArguments>("right")

}


public class Cabin_Lights_Row4: Model {

    typealias PartialType = Vehicle_Cabin_Lights_Row4

    public let isSharedOn: Bool?
    public let left: Cabin_Lights_Row4_Left?
    public let right: Cabin_Lights_Row4_Right?

    required init?(partial: Partial<PartialType?>) {
        isSharedOn = partial.isSharedOn ?? nil
        left = Cabin_Lights_Row4_Left(partial: partial.left)
        right = Cabin_Lights_Row4_Right(partial: partial.right)
    }
}
