import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_ADAS_CruiseControl {
     """
     Indicates if cruise control system incurred and error condition. True = Error. False = NoError.
     """
     error: Boolean
     """
     Indicates if cruise control system is enabled. True = Enabled. False = Disabled.
     """
     isActive: Boolean
     """
     Set cruise control speed in kilometers per hour
     """
     speedSet: Float
   }
*/

final class Vehicle_ADAS_CruiseControl: Object, ObjectSchema {

    /**
    Indicates if cruise control system incurred and error condition. True = Error. False = NoError.
    */
    var error = Field<Bool?, NoArguments>("error")

    /**
    Indicates if cruise control system is enabled. True = Enabled. False = Disabled.
    */
    var isActive = Field<Bool?, NoArguments>("isActive")

    /**
    Set cruise control speed in kilometers per hour
    */
    var speedSet = Field<Float?, NoArguments>("speedSet")

}


public class ADAS_CruiseControl: Model {

    typealias PartialType = Vehicle_ADAS_CruiseControl

    public let error: Bool?
    public let isActive: Bool?
    public let speedSet: Float?

    required init?(partial: Partial<PartialType?>) {
        error = partial.error ?? nil
        isActive = partial.isActive ?? nil
        speedSet = partial.speedSet ?? nil
    }
}
