import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    enum Vehicle_OBD_DriveCycleStatus_IgnitionType_Enum {
     spark
     compression
   }
*/

public enum Vehicle_OBD_DriveCycleStatus_IgnitionType_Enum: String, Enum {
   case spark = "spark"
   case compression = "compression"
}

public typealias OBD_DriveCycleStatus_IgnitionType_Enum = Vehicle_OBD_DriveCycleStatus_IgnitionType_Enum
