import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_AngularVelocity {
     """
     Vehicle rotation rate along Y (lateral).
     """
     pitch: Int
     """
     Vehicle rotation rate along X (longitudinal).
     """
     roll: Int
     """
     Vehicle rotation rate along Z (vertical).
     """
     yaw: Int
   }
*/

final class Vehicle_AngularVelocity: Object, ObjectSchema {

    /**
    Vehicle rotation rate along Y (lateral).
    */
    var pitch = Field<Int?, NoArguments>("pitch")

    /**
    Vehicle rotation rate along X (longitudinal).
    */
    var roll = Field<Int?, NoArguments>("roll")

    /**
    Vehicle rotation rate along Z (vertical).
    */
    var yaw = Field<Int?, NoArguments>("yaw")

}


public class AngularVelocity: Model {

    typealias PartialType = Vehicle_AngularVelocity

    public let pitch: Int?
    public let roll: Int?
    public let yaw: Int?

    required init?(partial: Partial<PartialType?>) {
        pitch = partial.pitch ?? nil
        roll = partial.roll ?? nil
        yaw = partial.yaw ?? nil
    }
}
