import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_OBD_O2_Bank2 {
     sensor1: Vehicle_OBD_O2_Bank2_Sensor1
     sensor2: Vehicle_OBD_O2_Bank2_Sensor2
     sensor3: Vehicle_OBD_O2_Bank2_Sensor3
     sensor4: Vehicle_OBD_O2_Bank2_Sensor4
   }
*/

final class Vehicle_OBD_O2_Bank2: Object, ObjectSchema {

    var sensor1 = Field<Vehicle_OBD_O2_Bank2_Sensor1?, NoArguments>("sensor1")

    var sensor2 = Field<Vehicle_OBD_O2_Bank2_Sensor2?, NoArguments>("sensor2")

    var sensor3 = Field<Vehicle_OBD_O2_Bank2_Sensor3?, NoArguments>("sensor3")

    var sensor4 = Field<Vehicle_OBD_O2_Bank2_Sensor4?, NoArguments>("sensor4")

}


public class OBD_O2_Bank2: Model {

    typealias PartialType = Vehicle_OBD_O2_Bank2

    public let sensor1: OBD_O2_Bank2_Sensor1?
    public let sensor2: OBD_O2_Bank2_Sensor2?
    public let sensor3: OBD_O2_Bank2_Sensor3?
    public let sensor4: OBD_O2_Bank2_Sensor4?

    required init?(partial: Partial<PartialType?>) {
        sensor1 = OBD_O2_Bank2_Sensor1(partial: partial.sensor1)
        sensor2 = OBD_O2_Bank2_Sensor2(partial: partial.sensor2)
        sensor3 = OBD_O2_Bank2_Sensor3(partial: partial.sensor3)
        sensor4 = OBD_O2_Bank2_Sensor4(partial: partial.sensor4)
    }
}
