import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Cabin_HVAC_Row1 {
     left: Vehicle_Cabin_HVAC_Row1_Left
     right: Vehicle_Cabin_HVAC_Row1_Right
   }
*/

final class Vehicle_Cabin_HVAC_Row1: Object, ObjectSchema {

    var left = Field<Vehicle_Cabin_HVAC_Row1_Left?, NoArguments>("left")

    var right = Field<Vehicle_Cabin_HVAC_Row1_Right?, NoArguments>("right")

}


public class Cabin_HVAC_Row1: Model {

    typealias PartialType = Vehicle_Cabin_HVAC_Row1

    public let left: Cabin_HVAC_Row1_Left?
    public let right: Cabin_HVAC_Row1_Right?

    required init?(partial: Partial<PartialType?>) {
        left = Cabin_HVAC_Row1_Left(partial: partial.left)
        right = Cabin_HVAC_Row1_Right(partial: partial.right)
    }
}
