import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Cabin_Infotainment_Navigation {
     currentLocation: Vehicle_Cabin_Infotainment_Navigation_CurrentLocation
     destinationSet: Vehicle_Cabin_Infotainment_Navigation_DestinationSet
   }
*/

final class Vehicle_Cabin_Infotainment_Navigation: Object, ObjectSchema {

    var currentLocation = Field<Vehicle_Cabin_Infotainment_Navigation_CurrentLocation?, NoArguments>("currentLocation")

    var destinationSet = Field<Vehicle_Cabin_Infotainment_Navigation_DestinationSet?, NoArguments>("destinationSet")

}


public class Cabin_Infotainment_Navigation: Model {

    typealias PartialType = Vehicle_Cabin_Infotainment_Navigation

    public let currentLocation: Cabin_Infotainment_Navigation_CurrentLocation?
    public let destinationSet: Cabin_Infotainment_Navigation_DestinationSet?

    required init?(partial: Partial<PartialType?>) {
        currentLocation = Cabin_Infotainment_Navigation_CurrentLocation(partial: partial.currentLocation)
        destinationSet = Cabin_Infotainment_Navigation_DestinationSet(partial: partial.destinationSet)
    }
}
