import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    enum Vehicle_Drivetrain_Transmission_Type_Enum {
     unknown
     sequential
     H
     automatic
     DSG
     CVT
   }
*/

public enum Vehicle_Drivetrain_Transmission_Type_Enum: String, Enum {
   case unknown = "unknown"
   case sequential = "sequential"
   case H = "H"
   case automatic = "automatic"
   case DSG = "DSG"
   case CVT = "CVT"
}

public typealias Drivetrain_Transmission_Type_Enum = Vehicle_Drivetrain_Transmission_Type_Enum
