import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Chassis_Accelerator {
     """
     Accelerator pedal position as percent. 0 = Not depressed. 100 = Fully depressed.
     """
     pedalPosition: Int
   }
*/

final class Vehicle_Chassis_Accelerator: Object, ObjectSchema {

    /**
    Accelerator pedal position as percent. 0 = Not depressed. 100 = Fully depressed.
    */
    var pedalPosition = Field<Int?, NoArguments>("pedalPosition")

}


public class Chassis_Accelerator: Model {

    typealias PartialType = Vehicle_Chassis_Accelerator

    public let pedalPosition: Int?

    required init?(partial: Partial<PartialType?>) {
        pedalPosition = partial.pedalPosition ?? nil
    }
}
