import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    enum Vehicle_Cabin_Infotainment_Media_Played_Source_Enum {
     unknown
     SiriusXM
     AM
     FM
     DAB
     TV
     CD
     DVD
     AUX
     USB
     Disk
     Bluetooth
     Internet
     Voice
     Beep
   }
*/

public enum Vehicle_Cabin_Infotainment_Media_Played_Source_Enum: String, Enum {
   case unknown = "unknown"
   case SiriusXM = "SiriusXM"
   case AM = "AM"
   case FM = "FM"
   case DAB = "DAB"
   case TV = "TV"
   case CD = "CD"
   case DVD = "DVD"
   case AUX = "AUX"
   case USB = "USB"
   case Disk = "Disk"
   case Bluetooth = "Bluetooth"
   case Internet = "Internet"
   case Voice = "Voice"
   case Beep = "Beep"
}

public typealias Cabin_Infotainment_Media_Played_Source_Enum = Vehicle_Cabin_Infotainment_Media_Played_Source_Enum
