import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_OBD_O2WR {
     sensor1: Vehicle_OBD_O2WR_Sensor1
     sensor2: Vehicle_OBD_O2WR_Sensor2
     sensor3: Vehicle_OBD_O2WR_Sensor3
     sensor4: Vehicle_OBD_O2WR_Sensor4
     sensor5: Vehicle_OBD_O2WR_Sensor5
     sensor6: Vehicle_OBD_O2WR_Sensor6
     sensor7: Vehicle_OBD_O2WR_Sensor7
     sensor8: Vehicle_OBD_O2WR_Sensor8
   }
*/

final class Vehicle_OBD_O2WR: Object, ObjectSchema {

    var sensor1 = Field<Vehicle_OBD_O2WR_Sensor1?, NoArguments>("sensor1")

    var sensor2 = Field<Vehicle_OBD_O2WR_Sensor2?, NoArguments>("sensor2")

    var sensor3 = Field<Vehicle_OBD_O2WR_Sensor3?, NoArguments>("sensor3")

    var sensor4 = Field<Vehicle_OBD_O2WR_Sensor4?, NoArguments>("sensor4")

    var sensor5 = Field<Vehicle_OBD_O2WR_Sensor5?, NoArguments>("sensor5")

    var sensor6 = Field<Vehicle_OBD_O2WR_Sensor6?, NoArguments>("sensor6")

    var sensor7 = Field<Vehicle_OBD_O2WR_Sensor7?, NoArguments>("sensor7")

    var sensor8 = Field<Vehicle_OBD_O2WR_Sensor8?, NoArguments>("sensor8")

}


public class OBD_O2WR: Model {

    typealias PartialType = Vehicle_OBD_O2WR

    public let sensor1: OBD_O2WR_Sensor1?
    public let sensor2: OBD_O2WR_Sensor2?
    public let sensor3: OBD_O2WR_Sensor3?
    public let sensor4: OBD_O2WR_Sensor4?
    public let sensor5: OBD_O2WR_Sensor5?
    public let sensor6: OBD_O2WR_Sensor6?
    public let sensor7: OBD_O2WR_Sensor7?
    public let sensor8: OBD_O2WR_Sensor8?

    required init?(partial: Partial<PartialType?>) {
        sensor1 = OBD_O2WR_Sensor1(partial: partial.sensor1)
        sensor2 = OBD_O2WR_Sensor2(partial: partial.sensor2)
        sensor3 = OBD_O2WR_Sensor3(partial: partial.sensor3)
        sensor4 = OBD_O2WR_Sensor4(partial: partial.sensor4)
        sensor5 = OBD_O2WR_Sensor5(partial: partial.sensor5)
        sensor6 = OBD_O2WR_Sensor6(partial: partial.sensor6)
        sensor7 = OBD_O2WR_Sensor7(partial: partial.sensor7)
        sensor8 = OBD_O2WR_Sensor8(partial: partial.sensor8)
    }
}
