import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    enum Vehicle_Drivetrain_Transmission_PerformanceMode_Enum {
     normal
     sport
     economy
     snow
     rain
   }
*/

public enum Vehicle_Drivetrain_Transmission_PerformanceMode_Enum: String, Enum {
   case normal = "normal"
   case sport = "sport"
   case economy = "economy"
   case snow = "snow"
   case rain = "rain"
}

public typealias Drivetrain_Transmission_PerformanceMode_Enum = Vehicle_Drivetrain_Transmission_PerformanceMode_Enum
