import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Drivetrain_InternalCombustionEngine {
     """
     Engine configuration.
     """
     configuration: Vehicle_Drivetrain_InternalCombustionEngine_Configuration_Enum
     """
     Displacement in cubic centimetres.
     """
     displacement: Int
     engine: Vehicle_Drivetrain_InternalCombustionEngine_Engine
     """
     Type of fuel that the engine runs on.
     """
     fuelType: Vehicle_Drivetrain_InternalCombustionEngine_FuelType_Enum
     """
     Peak power, in kilowatts, that engine can generate.
     """
     maxPower: Int
     """
     Peak power, in newton meter, that the engine can generate.
     """
     maxTorque: Int
   }
*/

final class Vehicle_Drivetrain_InternalCombustionEngine: Object, ObjectSchema {

    /**
    Engine configuration.
    */
    var configuration = Field<Vehicle_Drivetrain_InternalCombustionEngine_Configuration_Enum?, NoArguments>("configuration")

    /**
    Displacement in cubic centimetres.
    */
    var displacement = Field<Int?, NoArguments>("displacement")

    var engine = Field<Vehicle_Drivetrain_InternalCombustionEngine_Engine?, NoArguments>("engine")

    /**
    Type of fuel that the engine runs on.
    */
    var fuelType = Field<Vehicle_Drivetrain_InternalCombustionEngine_FuelType_Enum?, NoArguments>("fuelType")

    /**
    Peak power, in kilowatts, that engine can generate.
    */
    var maxPower = Field<Int?, NoArguments>("maxPower")

    /**
    Peak power, in newton meter, that the engine can generate.
    */
    var maxTorque = Field<Int?, NoArguments>("maxTorque")

}


public class Drivetrain_InternalCombustionEngine: Model {

    typealias PartialType = Vehicle_Drivetrain_InternalCombustionEngine

    public let configuration: Drivetrain_InternalCombustionEngine_Configuration_Enum?
    public let displacement: Int?
    public let engine: Drivetrain_InternalCombustionEngine_Engine?
    public let fuelType: Drivetrain_InternalCombustionEngine_FuelType_Enum?
    public let maxPower: Int?
    public let maxTorque: Int?

    required init?(partial: Partial<PartialType?>) {
        configuration = partial.configuration ?? nil
        displacement = partial.displacement ?? nil
        engine = Drivetrain_InternalCombustionEngine_Engine(partial: partial.engine)
        fuelType = partial.fuelType ?? nil
        maxPower = partial.maxPower ?? nil
        maxTorque = partial.maxTorque ?? nil
    }
}
