import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_OBD_O2WR_Sensor7 {
     """
     PID 3A - Lambda current for wide range/band oxygen sensor 7
     """
     current: Float
     """
     PID 2A - Lambda voltage for wide range/band oxygen sensor 7
     """
     voltage: Float
   }
*/

final class Vehicle_OBD_O2WR_Sensor7: Object, ObjectSchema {

    /**
    PID 3A - Lambda current for wide range/band oxygen sensor 7
    */
    var current = Field<Float?, NoArguments>("current")

    /**
    PID 2A - Lambda voltage for wide range/band oxygen sensor 7
    */
    var voltage = Field<Float?, NoArguments>("voltage")

}


public class OBD_O2WR_Sensor7: Model {

    typealias PartialType = Vehicle_OBD_O2WR_Sensor7

    public let current: Float?
    public let voltage: Float?

    required init?(partial: Partial<PartialType?>) {
        current = partial.current ?? nil
        voltage = partial.voltage ?? nil
    }
}
