import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    enum Vehicle_Cabin_Infotainment_HMI_DayNightMode_Enum {
     Day
     Night
   }
*/

public enum Vehicle_Cabin_Infotainment_HMI_DayNightMode_Enum: String, Enum {
   case Day = "Day"
   case Night = "Night"
}

public typealias Cabin_Infotainment_HMI_DayNightMode_Enum = Vehicle_Cabin_Infotainment_HMI_DayNightMode_Enum
