import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Cabin_Seat_Row1_Pos4_Switch_HeadRestraint {
     """
     Head restraint down switch engaged
     """
     down: Boolean
     """
     Head restraint up switch engaged
     """
     up: Boolean
   }
*/

final class Vehicle_Cabin_Seat_Row1_Pos4_Switch_HeadRestraint: Object, ObjectSchema {

    /**
    Head restraint down switch engaged
    */
    var down = Field<Bool?, NoArguments>("down")

    /**
    Head restraint up switch engaged
    */
    var up = Field<Bool?, NoArguments>("up")

}


public class Cabin_Seat_Row1_Pos4_Switch_HeadRestraint: Model {

    typealias PartialType = Vehicle_Cabin_Seat_Row1_Pos4_Switch_HeadRestraint

    public let down: Bool?
    public let up: Bool?

    required init?(partial: Partial<PartialType?>) {
        down = partial.down ?? nil
        up = partial.up ?? nil
    }
}
