import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    enum Vehicle_Drivetrain_Transmission_DriveType_Enum {
     unknown
     forward_wheel_drive
     rear_wheel_drive
     all_wheel_drive
   }
*/

public enum Vehicle_Drivetrain_Transmission_DriveType_Enum: String, Enum {
   case unknown = "unknown"
   case forward_wheel_drive = "forward_wheel_drive"
   case rear_wheel_drive = "rear_wheel_drive"
   case all_wheel_drive = "all_wheel_drive"
}

public typealias Drivetrain_Transmission_DriveType_Enum = Vehicle_Drivetrain_Transmission_DriveType_Enum
