import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    enum Vehicle_Body_Windshield_Rear_Wiping_Status_Enum {
     off
     slow
     medium
     fast
     interval
     rainsensor
   }
*/

public enum Vehicle_Body_Windshield_Rear_Wiping_Status_Enum: String, Enum {
   case off = "off"
   case slow = "slow"
   case medium = "medium"
   case fast = "fast"
   case interval = "interval"
   case rainsensor = "rainsensor"
}

public typealias Body_Windshield_Rear_Wiping_Status_Enum = Vehicle_Body_Windshield_Rear_Wiping_Status_Enum
