import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Drivetrain {
     batteryManagement: Vehicle_Drivetrain_BatteryManagement
     electricMotor: Vehicle_Drivetrain_ElectricMotor
     fuelCell: Vehicle_Drivetrain_FuelCell
     fuelSystem: Vehicle_Drivetrain_FuelSystem
     internalCombustionEngine: Vehicle_Drivetrain_InternalCombustionEngine
     transmission: Vehicle_Drivetrain_Transmission
   }
*/

final class Vehicle_Drivetrain: Object, ObjectSchema {

    var batteryManagement = Field<Vehicle_Drivetrain_BatteryManagement?, NoArguments>("batteryManagement")

    var electricMotor = Field<Vehicle_Drivetrain_ElectricMotor?, NoArguments>("electricMotor")

    var fuelCell = Field<Vehicle_Drivetrain_FuelCell?, NoArguments>("fuelCell")

    var fuelSystem = Field<Vehicle_Drivetrain_FuelSystem?, NoArguments>("fuelSystem")

    var internalCombustionEngine = Field<Vehicle_Drivetrain_InternalCombustionEngine?, NoArguments>("internalCombustionEngine")

    var transmission = Field<Vehicle_Drivetrain_Transmission?, NoArguments>("transmission")

}


public class Drivetrain: Model {

    typealias PartialType = Vehicle_Drivetrain

    public let batteryManagement: Drivetrain_BatteryManagement?
    public let electricMotor: Drivetrain_ElectricMotor?
    public let fuelCell: Drivetrain_FuelCell?
    public let fuelSystem: Drivetrain_FuelSystem?
    public let internalCombustionEngine: Drivetrain_InternalCombustionEngine?
    public let transmission: Drivetrain_Transmission?

    required init?(partial: Partial<PartialType?>) {
        batteryManagement = Drivetrain_BatteryManagement(partial: partial.batteryManagement)
        electricMotor = Drivetrain_ElectricMotor(partial: partial.electricMotor)
        fuelCell = Drivetrain_FuelCell(partial: partial.fuelCell)
        fuelSystem = Drivetrain_FuelSystem(partial: partial.fuelSystem)
        internalCombustionEngine = Drivetrain_InternalCombustionEngine(partial: partial.internalCombustionEngine)
        transmission = Drivetrain_Transmission(partial: partial.transmission)
    }
}
