import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Cabin_Sunroof {
     """
     Sunroof position. 0 = Fully closed 100 = Fully opened. -100 = Fully tilted
     """
     position: Int
     shade: Vehicle_Cabin_Sunroof_Shade
     """
     Switch controlling sliding action such as window, sunroof, or shade.
     """
     switch: Vehicle_Cabin_Sunroof_Switch_Enum
   }
*/

final class Vehicle_Cabin_Sunroof: Object, ObjectSchema {

    /**
    Sunroof position. 0 = Fully closed 100 = Fully opened. -100 = Fully tilted
    */
    var position = Field<Int?, NoArguments>("position")

    var shade = Field<Vehicle_Cabin_Sunroof_Shade?, NoArguments>("shade")

    /**
    Switch controlling sliding action such as window, sunroof, or shade.
    */
    var `switch` = Field<Vehicle_Cabin_Sunroof_Switch_Enum?, NoArguments>("switch")

}


public class Cabin_Sunroof: Model {

    typealias PartialType = Vehicle_Cabin_Sunroof

    public let position: Int?
    public let shade: Cabin_Sunroof_Shade?
    public let `switch`: Cabin_Sunroof_Switch_Enum?

    required init?(partial: Partial<PartialType?>) {
        position = partial.position ?? nil
        shade = Cabin_Sunroof_Shade(partial: partial.shade)
        `switch` = partial.`switch` ?? nil
    }
}
