import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Cabin_Infotainment_Media_Played {
     """
     Name of album being played
     """
     album: String
     """
     Name of artist being played
     """
     artist: String
     """
     Media selected for playback
     """
     source: Vehicle_Cabin_Infotainment_Media_Played_Source_Enum
     """
     Name of track being played
     """
     track: String
     """
     User Resource associated with the media
     """
     uri: String
   }
*/

final class Vehicle_Cabin_Infotainment_Media_Played: Object, ObjectSchema {

    /**
    Name of album being played
    */
    var album = Field<String?, NoArguments>("album")

    /**
    Name of artist being played
    */
    var artist = Field<String?, NoArguments>("artist")

    /**
    Media selected for playback
    */
    var source = Field<Vehicle_Cabin_Infotainment_Media_Played_Source_Enum?, NoArguments>("source")

    /**
    Name of track being played
    */
    var track = Field<String?, NoArguments>("track")

    /**
    User Resource associated with the media
    */
    var uri = Field<String?, NoArguments>("uri")

}


public class Cabin_Infotainment_Media_Played: Model {

    typealias PartialType = Vehicle_Cabin_Infotainment_Media_Played

    public let album: String?
    public let artist: String?
    public let source: Cabin_Infotainment_Media_Played_Source_Enum?
    public let track: String?
    public let uri: String?

    required init?(partial: Partial<PartialType?>) {
        album = partial.album ?? nil
        artist = partial.artist ?? nil
        source = partial.source ?? nil
        track = partial.track ?? nil
        uri = partial.uri ?? nil
    }
}
