import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Body_Trunk {
     """
     Is trunk locked or unlocked. True = Locked. False = Unlocked.
     """
     isLocked: Boolean
     """
     Trunk open or closed. True = Open. False = Closed
     """
     isOpen: Boolean
   }
*/

final class Vehicle_Body_Trunk: Object, ObjectSchema {

    /**
    Is trunk locked or unlocked. True = Locked. False = Unlocked.
    */
    var isLocked = Field<Bool?, NoArguments>("isLocked")

    /**
    Trunk open or closed. True = Open. False = Closed
    */
    var isOpen = Field<Bool?, NoArguments>("isOpen")

}


public class Body_Trunk: Model {

    typealias PartialType = Vehicle_Body_Trunk

    public let isLocked: Bool?
    public let isOpen: Bool?

    required init?(partial: Partial<PartialType?>) {
        isLocked = partial.isLocked ?? nil
        isOpen = partial.isOpen ?? nil
    }
}
