import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Cabin_SteeringWheel {
     """
     Position of the steering wheel inside the cabin
     """
     position: Vehicle_Cabin_SteeringWheel_Position_Enum
   }
*/

final class Vehicle_Cabin_SteeringWheel: Object, ObjectSchema {

    /**
    Position of the steering wheel inside the cabin
    */
    var position = Field<Vehicle_Cabin_SteeringWheel_Position_Enum?, NoArguments>("position")

}


public class Cabin_SteeringWheel: Model {

    typealias PartialType = Vehicle_Cabin_SteeringWheel

    public let position: Cabin_SteeringWheel_Position_Enum?

    required init?(partial: Partial<PartialType?>) {
        position = partial.position ?? nil
    }
}
