import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Chassis_Axle_Row1_Wheel_Right_Tire {
     """
     Tire pressure in kilo-Pascal
     """
     pressure: Int
     """
     Tire Pressure Status. True = Low tire pressure. False = Good tire pressure.
     """
     pressureLow: Boolean
     """
     Tire temperature in Celsius.
     """
     temperature: Float
   }
*/

final class Vehicle_Chassis_Axle_Row1_Wheel_Right_Tire: Object, ObjectSchema {

    /**
    Tire pressure in kilo-Pascal
    */
    var pressure = Field<Int?, NoArguments>("pressure")

    /**
    Tire Pressure Status. True = Low tire pressure. False = Good tire pressure.
    */
    var pressureLow = Field<Bool?, NoArguments>("pressureLow")

    /**
    Tire temperature in Celsius.
    */
    var temperature = Field<Float?, NoArguments>("temperature")

}


public class Chassis_Axle_Row1_Wheel_Right_Tire: Model {

    typealias PartialType = Vehicle_Chassis_Axle_Row1_Wheel_Right_Tire

    public let pressure: Int?
    public let pressureLow: Bool?
    public let temperature: Float?

    required init?(partial: Partial<PartialType?>) {
        pressure = partial.pressure ?? nil
        pressureLow = partial.pressureLow ?? nil
        temperature = partial.temperature ?? nil
    }
}
