import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    enum Vehicle_Cabin_SteeringWheel_Position_Enum {
     front_left
     front_right
   }
*/

public enum Vehicle_Cabin_SteeringWheel_Position_Enum: String, Enum {
   case front_left = "front_left"
   case front_right = "front_right"
}

public typealias Cabin_SteeringWheel_Position_Enum = Vehicle_Cabin_SteeringWheel_Position_Enum
