import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Cabin {
     convertible: Vehicle_Cabin_Convertible
     door: Vehicle_Cabin_Door
     hvac: Vehicle_Cabin_HVAC
     infotainment: Vehicle_Cabin_Infotainment
     lights: Vehicle_Cabin_Lights
     rearShade: Vehicle_Cabin_RearShade
     rearviewMirror: Vehicle_Cabin_RearviewMirror
     seat: Vehicle_Cabin_Seat
     steeringWheel: Vehicle_Cabin_SteeringWheel
     sunroof: Vehicle_Cabin_Sunroof
   }
*/

final class Vehicle_Cabin: Object, ObjectSchema {

    var convertible = Field<Vehicle_Cabin_Convertible?, NoArguments>("convertible")

    var door = Field<Vehicle_Cabin_Door?, NoArguments>("door")

    var hvac = Field<Vehicle_Cabin_HVAC?, NoArguments>("hvac")

    var infotainment = Field<Vehicle_Cabin_Infotainment?, NoArguments>("infotainment")

    var lights = Field<Vehicle_Cabin_Lights?, NoArguments>("lights")

    var rearShade = Field<Vehicle_Cabin_RearShade?, NoArguments>("rearShade")

    var rearviewMirror = Field<Vehicle_Cabin_RearviewMirror?, NoArguments>("rearviewMirror")

    var seat = Field<Vehicle_Cabin_Seat?, NoArguments>("seat")

    var steeringWheel = Field<Vehicle_Cabin_SteeringWheel?, NoArguments>("steeringWheel")

    var sunroof = Field<Vehicle_Cabin_Sunroof?, NoArguments>("sunroof")

}


public class Cabin: Model {

    typealias PartialType = Vehicle_Cabin

    public let convertible: Cabin_Convertible?
    public let door: Cabin_Door?
    public let hvac: Cabin_HVAC?
    public let infotainment: Cabin_Infotainment?
    public let lights: Cabin_Lights?
    public let rearShade: Cabin_RearShade?
    public let rearviewMirror: Cabin_RearviewMirror?
    public let seat: Cabin_Seat?
    public let steeringWheel: Cabin_SteeringWheel?
    public let sunroof: Cabin_Sunroof?

    required init?(partial: Partial<PartialType?>) {
        convertible = Cabin_Convertible(partial: partial.convertible)
        door = Cabin_Door(partial: partial.door)
        hvac = Cabin_HVAC(partial: partial.hvac)
        infotainment = Cabin_Infotainment(partial: partial.infotainment)
        lights = Cabin_Lights(partial: partial.lights)
        rearShade = Cabin_RearShade(partial: partial.rearShade)
        rearviewMirror = Cabin_RearviewMirror(partial: partial.rearviewMirror)
        seat = Cabin_Seat(partial: partial.seat)
        steeringWheel = Cabin_SteeringWheel(partial: partial.steeringWheel)
        sunroof = Cabin_Sunroof(partial: partial.sunroof)
    }
}
