import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Cabin_Seat_Row4_Pos3_Switch_Massage {
     """
     Decrease massage level switch engaged
     """
     decrease: Boolean
     """
     Increase massage level switch engaged
     """
     increase: Boolean
   }
*/

final class Vehicle_Cabin_Seat_Row4_Pos3_Switch_Massage: Object, ObjectSchema {

    /**
    Decrease massage level switch engaged
    */
    var decrease = Field<Bool?, NoArguments>("decrease")

    /**
    Increase massage level switch engaged
    */
    var increase = Field<Bool?, NoArguments>("increase")

}


public class Cabin_Seat_Row4_Pos3_Switch_Massage: Model {

    typealias PartialType = Vehicle_Cabin_Seat_Row4_Pos3_Switch_Massage

    public let decrease: Bool?
    public let increase: Bool?

    required init?(partial: Partial<PartialType?>) {
        decrease = partial.decrease ?? nil
        increase = partial.increase ?? nil
    }
}
