import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Cabin_Infotainment {
     hmi: Vehicle_Cabin_Infotainment_HMI
     media: Vehicle_Cabin_Infotainment_Media
     navigation: Vehicle_Cabin_Infotainment_Navigation
   }
*/

final class Vehicle_Cabin_Infotainment: Object, ObjectSchema {

    var hmi = Field<Vehicle_Cabin_Infotainment_HMI?, NoArguments>("hmi")

    var media = Field<Vehicle_Cabin_Infotainment_Media?, NoArguments>("media")

    var navigation = Field<Vehicle_Cabin_Infotainment_Navigation?, NoArguments>("navigation")

}


public class Cabin_Infotainment: Model {

    typealias PartialType = Vehicle_Cabin_Infotainment

    public let hmi: Cabin_Infotainment_HMI?
    public let media: Cabin_Infotainment_Media?
    public let navigation: Cabin_Infotainment_Navigation?

    required init?(partial: Partial<PartialType?>) {
        hmi = Cabin_Infotainment_HMI(partial: partial.hmi)
        media = Cabin_Infotainment_Media(partial: partial.media)
        navigation = Cabin_Infotainment_Navigation(partial: partial.navigation)
    }
}
