import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_ADAS {
     abs: Vehicle_ADAS_ABS
     cruiseControl: Vehicle_ADAS_CruiseControl
     esc: Vehicle_ADAS_ESC
     laneDepartureDetection: Vehicle_ADAS_LaneDepartureDetection
     obstacleDetection: Vehicle_ADAS_ObstacleDetection
     tcs: Vehicle_ADAS_TCS
   }
*/

final class Vehicle_ADAS: Object, ObjectSchema {

    var abs = Field<Vehicle_ADAS_ABS?, NoArguments>("abs")

    var cruiseControl = Field<Vehicle_ADAS_CruiseControl?, NoArguments>("cruiseControl")

    var esc = Field<Vehicle_ADAS_ESC?, NoArguments>("esc")

    var laneDepartureDetection = Field<Vehicle_ADAS_LaneDepartureDetection?, NoArguments>("laneDepartureDetection")

    var obstacleDetection = Field<Vehicle_ADAS_ObstacleDetection?, NoArguments>("obstacleDetection")

    var tcs = Field<Vehicle_ADAS_TCS?, NoArguments>("tcs")

}


public class ADAS: Model {

    typealias PartialType = Vehicle_ADAS

    public let abs: ADAS_ABS?
    public let cruiseControl: ADAS_CruiseControl?
    public let esc: ADAS_ESC?
    public let laneDepartureDetection: ADAS_LaneDepartureDetection?
    public let obstacleDetection: ADAS_ObstacleDetection?
    public let tcs: ADAS_TCS?

    required init?(partial: Partial<PartialType?>) {
        abs = ADAS_ABS(partial: partial.abs)
        cruiseControl = ADAS_CruiseControl(partial: partial.cruiseControl)
        esc = ADAS_ESC(partial: partial.esc)
        laneDepartureDetection = ADAS_LaneDepartureDetection(partial: partial.laneDepartureDetection)
        obstacleDetection = ADAS_ObstacleDetection(partial: partial.obstacleDetection)
        tcs = ADAS_TCS(partial: partial.tcs)
    }
}
