import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Cabin_Infotainment_Media {
     """
     Tells if the media was
     """
     action: Vehicle_Cabin_Infotainment_Media_Action_Enum
     """
     URI of suggested media that was declined
     """
     declinedURI: String
     played: Vehicle_Cabin_Infotainment_Media_Played
     """
     URI of suggested media that was selected
     """
     selectedURI: String
     """
     Current Media Volume
     """
     volume: Int
   }
*/

final class Vehicle_Cabin_Infotainment_Media: Object, ObjectSchema {

    /**
    Tells if the media was
    */
    var action = Field<Vehicle_Cabin_Infotainment_Media_Action_Enum?, NoArguments>("action")

    /**
    URI of suggested media that was declined
    */
    var declinedURI = Field<String?, NoArguments>("declinedURI")

    var played = Field<Vehicle_Cabin_Infotainment_Media_Played?, NoArguments>("played")

    /**
    URI of suggested media that was selected
    */
    var selectedURI = Field<String?, NoArguments>("selectedURI")

    /**
    Current Media Volume
    */
    var volume = Field<Int?, NoArguments>("volume")

}


public class Cabin_Infotainment_Media: Model {

    typealias PartialType = Vehicle_Cabin_Infotainment_Media

    public let action: Cabin_Infotainment_Media_Action_Enum?
    public let declinedURI: String?
    public let played: Cabin_Infotainment_Media_Played?
    public let selectedURI: String?
    public let volume: Int?

    required init?(partial: Partial<PartialType?>) {
        action = partial.action ?? nil
        declinedURI = partial.declinedURI ?? nil
        played = Cabin_Infotainment_Media_Played(partial: partial.played)
        selectedURI = partial.selectedURI ?? nil
        volume = partial.volume ?? nil
    }
}
