import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    enum Vehicle_Cabin_Infotainment_Media_Action_Enum {
     unknown
     Stop
     Play
     FastForward
     FastBackward
     SkipForward
     SkipBackward
   }
*/

public enum Vehicle_Cabin_Infotainment_Media_Action_Enum: String, Enum {
   case unknown = "unknown"
   case Stop = "Stop"
   case Play = "Play"
   case FastForward = "FastForward"
   case FastBackward = "FastBackward"
   case SkipForward = "SkipForward"
   case SkipBackward = "SkipBackward"
}

public typealias Cabin_Infotainment_Media_Action_Enum = Vehicle_Cabin_Infotainment_Media_Action_Enum
