import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    enum Vehicle_Cabin_Infotainment_HMI_TimeFormat_Enum {
     _12HR
     _24HR
   }
*/

public enum Vehicle_Cabin_Infotainment_HMI_TimeFormat_Enum: String, Enum {
   case _12HR = "_12HR"
   case _24HR = "_24HR"
}

public typealias Cabin_Infotainment_HMI_TimeFormat_Enum = Vehicle_Cabin_Infotainment_HMI_TimeFormat_Enum
