import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Cabin_Lights_Row3 {
     """
     Is light shared third across row on
     """
     isSharedOn: Boolean
     left: Vehicle_Cabin_Lights_Row3_Left
     right: Vehicle_Cabin_Lights_Row3_Right
   }
*/

final class Vehicle_Cabin_Lights_Row3: Object, ObjectSchema {

    /**
    Is light shared third across row on
    */
    var isSharedOn = Field<Bool?, NoArguments>("isSharedOn")

    var left = Field<Vehicle_Cabin_Lights_Row3_Left?, NoArguments>("left")

    var right = Field<Vehicle_Cabin_Lights_Row3_Right?, NoArguments>("right")

}


public class Cabin_Lights_Row3: Model {

    typealias PartialType = Vehicle_Cabin_Lights_Row3

    public let isSharedOn: Bool?
    public let left: Cabin_Lights_Row3_Left?
    public let right: Cabin_Lights_Row3_Right?

    required init?(partial: Partial<PartialType?>) {
        isSharedOn = partial.isSharedOn ?? nil
        left = Cabin_Lights_Row3_Left(partial: partial.left)
        right = Cabin_Lights_Row3_Right(partial: partial.right)
    }
}
