import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_Cabin_Door {
     """
     Number of doors in vehicle
     """
     count: Int
     row1: Vehicle_Cabin_Door_Row1
     row2: Vehicle_Cabin_Door_Row2
     row3: Vehicle_Cabin_Door_Row3
     row4: Vehicle_Cabin_Door_Row4
   }
*/

final class Vehicle_Cabin_Door: Object, ObjectSchema {

    /**
    Number of doors in vehicle
    */
    var count = Field<Int?, NoArguments>("count")

    var row1 = Field<Vehicle_Cabin_Door_Row1?, NoArguments>("row1")

    var row2 = Field<Vehicle_Cabin_Door_Row2?, NoArguments>("row2")

    var row3 = Field<Vehicle_Cabin_Door_Row3?, NoArguments>("row3")

    var row4 = Field<Vehicle_Cabin_Door_Row4?, NoArguments>("row4")

}


public class Cabin_Door: Model {

    typealias PartialType = Vehicle_Cabin_Door

    public let count: Int?
    public let row1: Cabin_Door_Row1?
    public let row2: Cabin_Door_Row2?
    public let row3: Cabin_Door_Row3?
    public let row4: Cabin_Door_Row4?

    required init?(partial: Partial<PartialType?>) {
        count = partial.count ?? nil
        row1 = Cabin_Door_Row1(partial: partial.row1)
        row2 = Cabin_Door_Row2(partial: partial.row2)
        row3 = Cabin_Door_Row3(partial: partial.row3)
        row4 = Cabin_Door_Row4(partial: partial.row4)
    }
}
