import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

    type Vehicle_OBD_O2WR_Sensor2 {
     """
     PID 35 - Lambda current for wide range/band oxygen sensor 2
     """
     current: Float
     """
     PID 25 - Lambda voltage for wide range/band oxygen sensor 2
     """
     voltage: Float
   }
*/

final class Vehicle_OBD_O2WR_Sensor2: Object, ObjectSchema {

    /**
    PID 35 - Lambda current for wide range/band oxygen sensor 2
    */
    var current = Field<Float?, NoArguments>("current")

    /**
    PID 25 - Lambda voltage for wide range/band oxygen sensor 2
    */
    var voltage = Field<Float?, NoArguments>("voltage")

}


public class OBD_O2WR_Sensor2: Model {

    typealias PartialType = Vehicle_OBD_O2WR_Sensor2

    public let current: Float?
    public let voltage: Float?

    required init?(partial: Partial<PartialType?>) {
        current = partial.current ?? nil
        voltage = partial.voltage ?? nil
    }
}
