import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   enum Vehicle_Drivetrain_InternalCombustionEngine_Configuration_Enum {
     unknown
     straight
     V
     boxer
     W
     rotary
     radial
     square
     H
     U
     opposed
     X
   }
*/

enum Vehicle_Drivetrain_InternalCombustionEngine_Configuration_Enum: String, Enum {
   case unknown = "unknown"
   case straight = "straight"
   case V = "V"
   case boxer = "boxer"
   case W = "W"
   case rotary = "rotary"
   case radial = "radial"
   case square = "square"
   case H = "H"
   case U = "U"
   case opposed = "opposed"
   case X = "X"
}
