import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Drivetrain {
     batteryManagement: Vehicle_Drivetrain_BatteryManagement
     electricMotor: Vehicle_Drivetrain_ElectricMotor
     fuelCell: Vehicle_Drivetrain_FuelCell
     fuelSystem: Vehicle_Drivetrain_FuelSystem
     internalCombustionEngine: Vehicle_Drivetrain_InternalCombustionEngine
     transmission: Vehicle_Drivetrain_Transmission
   }
*/

final class Vehicle_Drivetrain: Object, ObjectSchema {

   var batteryManagement = Field<Vehicle_Drivetrain_BatteryManagement?, NoArguments>("batteryManagement")

   var electricMotor = Field<Vehicle_Drivetrain_ElectricMotor?, NoArguments>("electricMotor")

   var fuelCell = Field<Vehicle_Drivetrain_FuelCell?, NoArguments>("fuelCell")

   var fuelSystem = Field<Vehicle_Drivetrain_FuelSystem?, NoArguments>("fuelSystem")

   var internalCombustionEngine = Field<Vehicle_Drivetrain_InternalCombustionEngine?, NoArguments>("internalCombustionEngine")

   var transmission = Field<Vehicle_Drivetrain_Transmission?, NoArguments>("transmission")
}
