import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Drivetrain_ElectricMotor {
     """
     Dummy description
     """
     dummyField: String
   }
*/

final class Vehicle_Drivetrain_ElectricMotor: Object, ObjectSchema {

   /**
    Dummy description
   */
   var dummyField = Field<String?, NoArguments>("dummyField")
}
