import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Drivetrain_Transmission {
     """
     Clutch wear as a percent. 0 = no wear. 100 = worn.
     """
     clutchWear: Int
     """
     Drive type.
     """
     driveType: Vehicle_Drivetrain_Transmission_DriveType_Enum
     """
     Current gear. 0=Neutral. -1=Reverse
     """
     gear: Int
     """
     Is the gearbox in automatic or manual (paddle) mode.
     """
     gearChangeMode: Vehicle_Drivetrain_Transmission_GearChangeMode_Enum
     """
     Number of forward gears in the transmission. -1 = CVT.
     """
     gearCount: Int
     """
     Current gearbox performance mode.
     """
     performanceMode: Vehicle_Drivetrain_Transmission_PerformanceMode_Enum
     """
     Vehicle speed, as sensed by the gearbox.
     """
     speed: Float
     """
     The current gearbox temperature
     """
     temperature: Int
     """
     Odometer reading
     """
     travelledDistance: Float
     """
     Transmission type.
     """
     type: Vehicle_Drivetrain_Transmission_Type_Enum
   }
*/

final class Vehicle_Drivetrain_Transmission: Object, ObjectSchema {

   /**
    Clutch wear as a percent. 0 = no wear. 100 = worn.
   */
   var clutchWear = Field<Int?, NoArguments>("clutchWear")

   /**
    Drive type.
   */
   var driveType = Field<Vehicle_Drivetrain_Transmission_DriveType_Enum?, NoArguments>("driveType")

   /**
    Current gear. 0=Neutral. -1=Reverse
   */
   var gear = Field<Int?, NoArguments>("gear")

   /**
    Is the gearbox in automatic or manual (paddle) mode.
   */
   var gearChangeMode = Field<Vehicle_Drivetrain_Transmission_GearChangeMode_Enum?, NoArguments>("gearChangeMode")

   /**
    Number of forward gears in the transmission. -1 = CVT.
   */
   var gearCount = Field<Int?, NoArguments>("gearCount")

   /**
    Current gearbox performance mode.
   */
   var performanceMode = Field<Vehicle_Drivetrain_Transmission_PerformanceMode_Enum?, NoArguments>("performanceMode")

   /**
    Vehicle speed, as sensed by the gearbox.
   */
   var speed = Field<Float?, NoArguments>("speed")

   /**
    The current gearbox temperature
   */
   var temperature = Field<Int?, NoArguments>("temperature")

   /**
    Odometer reading
   */
   var travelledDistance = Field<Float?, NoArguments>("travelledDistance")

   /**
    Transmission type.
   */
   var transmissionType = Field<Vehicle_Drivetrain_Transmission_Type_Enum?, NoArguments>("type")
}
