import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   enum Vehicle_Cabin_Sunroof_Switch_Enum {
     Inactive
     Close
     Open
     OneShotClose
     OneShotOpen
     TiltUp
     TiltDown
   }
*/

enum Vehicle_Cabin_Sunroof_Switch_Enum: String, Enum {
   case Inactive = "Inactive"
   case Close = "Close"
   case Open = "Open"
   case OneShotClose = "OneShotClose"
   case OneShotOpen = "OneShotOpen"
   case TiltUp = "TiltUp"
   case TiltDown = "TiltDown"
}
