import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Cabin_Sunroof_Shade {
     """
     Position of side window blind. 0 = Fully retracted. 100 = Fully deployed.
     """
     position: Int
     """
     Switch controlling sliding action such as window, sunroof, or blind.
     """
     switch: Vehicle_Cabin_Sunroof_Shade_Switch_Enum
   }
*/

final class Vehicle_Cabin_Sunroof_Shade: Object, ObjectSchema {

   /**
    Position of side window blind. 0 = Fully retracted. 100 = Fully deployed.
   */
   var position = Field<Int?, NoArguments>("position")

   /**
    Switch controlling sliding action such as window, sunroof, or blind.
   */
   var shadeSwitch = Field<Vehicle_Cabin_Sunroof_Shade_Switch_Enum?, NoArguments>("switch")
}
