import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Body_Mirrors_Left_Heating {
     """
     Mirror Heater on or off. True = Heater On. False = Heater Off.
     """
     status: Boolean
   }
*/

final class Vehicle_Body_Mirrors_Left_Heating: Object, ObjectSchema {

   /**
    Mirror Heater on or off. True = Heater On. False = Heater Off.
   */
   var status = Field<Bool?, NoArguments>("status")
}
