import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Body_Windshield_Front_Wiping {
     """
     Front wiper status
     """
     status: Vehicle_Body_Windshield_Front_Wiping_Status_Enum
   }
*/

final class Vehicle_Body_Windshield_Front_Wiping: Object, ObjectSchema {

   /**
    Front wiper status
   */
   var status = Field<Vehicle_Body_Windshield_Front_Wiping_Status_Enum?, NoArguments>("status")
}
