import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Body_Hood {
     """
     hood open or closed. True = Open. False = Closed
     """
     isOpen: Boolean
   }
*/

final class Vehicle_Body_Hood: Object, ObjectSchema {

   /**
    hood open or closed. True = Open. False = Closed
   */
   var isOpen = Field<Bool?, NoArguments>("isOpen")
}
