import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Body_Windshield_Rear_Heating {
     """
     Rear windshield heater status. 0 - off, 1 - on
     """
     status: Boolean
   }
*/

final class Vehicle_Body_Windshield_Rear_Heating: Object, ObjectSchema {

   /**
    Rear windshield heater status. 0 - off, 1 - on
   */
   var status = Field<Bool?, NoArguments>("status")
}
