import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Body_Windshield {
     front: Vehicle_Body_Windshield_Front
     rear: Vehicle_Body_Windshield_Rear
   }
*/

final class Vehicle_Body_Windshield: Object, ObjectSchema {

   var front = Field<Vehicle_Body_Windshield_Front?, NoArguments>("front")

   var rear = Field<Vehicle_Body_Windshield_Rear?, NoArguments>("rear")
}
