import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Body_Raindetection {
     """
     Rain intensity. 0 = Dry, No Rain. 100 = Covered.
     """
     intensity: Int
   }
*/

final class Vehicle_Body_Raindetection: Object, ObjectSchema {

   /**
    Rain intensity. 0 = Dry, No Rain. 100 = Covered.
   */
   var intensity = Field<Int?, NoArguments>("intensity")
}
