import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Body_Mirrors {
     left: Vehicle_Body_Mirrors_Left
     right: Vehicle_Body_Mirrors_Right
   }
*/

final class Vehicle_Body_Mirrors: Object, ObjectSchema {

   var left = Field<Vehicle_Body_Mirrors_Left?, NoArguments>("left")

   var right = Field<Vehicle_Body_Mirrors_Right?, NoArguments>("right")
}
