import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Body_Horn {
     """
     Horn active or inactive. True = Active. False = Inactive.
     """
     isActive: Boolean
   }
*/

final class Vehicle_Body_Horn: Object, ObjectSchema {

   /**
    Horn active or inactive. True = Active. False = Inactive.
   */
   var isActive = Field<Bool?, NoArguments>("isActive")
}
