import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   enum Vehicle_Cabin_Infotainment_HMI_DateFormat_Enum {
     YYYY_MM_DD
     DD_MM_YYYY
     MM_DD_YYYY
     YY_MM_DD
     DD_MM_YY
     MM_DD_YY
   }
*/

enum Vehicle_Cabin_Infotainment_HMI_DateFormat_Enum: String, Enum {
   case YYYY_MM_DD = "YYYY_MM_DD"
   case DD_MM_YYYY = "DD_MM_YYYY"
   case MM_DD_YYYY = "MM_DD_YYYY"
   case YY_MM_DD = "YY_MM_DD"
   case DD_MM_YY = "DD_MM_YY"
   case MM_DD_YY = "MM_DD_YY"
}
