import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   enum Vehicle_Cabin_Infotainment_HMI_DayNightMode_Enum {
     Day
     Night
   }
*/

enum Vehicle_Cabin_Infotainment_HMI_DayNightMode_Enum: String, Enum {
   case Day = "Day"
   case Night = "Night"
}
