import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Cabin_Infotainment_Navigation_DestinationSet {
     """
     Latitude of destination
     """
     latitude: Float
     """
     Longitude of destination
     """
     longitude: Float
   }
*/

final class Vehicle_Cabin_Infotainment_Navigation_DestinationSet: Object, ObjectSchema {

   /**
    Latitude of destination
   */
   var latitude = Field<Float?, NoArguments>("latitude")

   /**
    Longitude of destination
   */
   var longitude = Field<Float?, NoArguments>("longitude")
}
