import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Cabin_Infotainment_Navigation {
     currentLocation: Vehicle_Cabin_Infotainment_Navigation_CurrentLocation
     destinationSet: Vehicle_Cabin_Infotainment_Navigation_DestinationSet
   }
*/

final class Vehicle_Cabin_Infotainment_Navigation: Object, ObjectSchema {

   var currentLocation = Field<Vehicle_Cabin_Infotainment_Navigation_CurrentLocation?, NoArguments>("currentLocation")

   var destinationSet = Field<Vehicle_Cabin_Infotainment_Navigation_DestinationSet?, NoArguments>("destinationSet")
}
