import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Acceleration {
     """
     Vehicle acceleration in Y (lateral acceleration).
     """
     lateral: Float
     """
     Vehicle acceleration in X (longitudinal acceleration).
     """
     longitudinal: Float
     """
     Vehicle acceleration in Z (vertical acceleration).
     """
     vertical: Float
   }
*/

final class Vehicle_Acceleration: Object, ObjectSchema {

   /**
    Vehicle acceleration in Y (lateral acceleration).
   */
   var lateral = Field<Float?, NoArguments>("lateral")

   /**
    Vehicle acceleration in X (longitudinal acceleration).
   */
   var longitudinal = Field<Float?, NoArguments>("longitudinal")

   /**
    Vehicle acceleration in Z (vertical acceleration).
   */
   var vertical = Field<Float?, NoArguments>("vertical")
}



protocol Model {

    associatedtype PartialType: SelectionOutput

    init?(partial: Partial<PartialType?>?)
    init?(partial: Partial<PartialType?>)
}

extension Model {

    init?(partial: Partial<PartialType?>?) {
        guard let partial = partial else {
            return nil
        }

        self.init(partial: partial)
    }
}


public class Acceleration: Model {

    typealias PartialType = Vehicle_Acceleration

    public let lateral: Float?
    public let longitudinal: Float?
    public let vertical: Float?


    required init?(partial: Partial<PartialType?>) {
        lateral = partial.lateral ?? nil
        longitudinal = partial.longitudinal ?? nil
        vertical = partial.vertical ?? nil
    }
}
