//
//  ADASCruiseControl.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct ADASCruiseControl: GraphQLType {

    /// Indicates if cruise control system incurred and error condition. True = Error. False = NoError.
    public var error: Bool? = nil

    /// Indicates if cruise control system is enabled. True = Enabled. False = Disabled.
    public var isActive: Bool? = nil

    /// Set cruise control speed in kilometers per hour
    public var speedSet: Float? = nil
}