//
//  ADASABS.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct ADASABS: GraphQLType {

    /// Indicates if ABS incurred an error condition. True = Error. False = No Error.
    public var error: Bool? = nil

    /// Indicates if ABS is enabled. True = Enabled. False = Disabled.
    public var isActive: Bool? = nil

    /// Indicates if ABS is currently regulating brake pressure. True = Engaged. False = Not Engaged.
    public var isEngaged: Bool? = nil
}