//
//  ADASObstacleDetectionDistanceToObject.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct ADASObstacleDetectionDistanceToObject: GraphQLObjectType {

    /// Front left distance to object in meters
    public var frontLeft: Int? = nil

    /// Front right distance to object in meters
    public var frontRight: Int? = nil

    /// Rear left distance to object in meters
    public var rearLeft: Int? = nil

    /// Rear right distance to object in meters
    public var rearRight: Int? = nil
}