//
//  ADAS.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct ADAS: GraphQLType {

    public var abs: ADASABS? = nil

    public var cruiseControl: ADASCruiseControl? = nil

    public var esc: ADASESC? = nil

    public var laneDepartureDetection: ADASLaneDepartureDetection? = nil

    public var obstacleDetection: ADASObstacleDetection? = nil

    public var tcs: ADASTCS? = nil
}