//
//  ADASObstacleDetection.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct ADASObstacleDetection: GraphQLType {

    public var distanceToObject: ADASObstacleDetectionDistanceToObject? = nil

    /// Indicates if obstacle sensor system incurred an error condition. True = Error. False = No Error.
    public var error: Bool? = nil

    /// Indicates if obstacle sensor system is enabled. True = Enabled. False = Disabled.
    public var isActive: Bool? = nil
}