//
//  ADASLaneDepartureDetection.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct ADASLaneDepartureDetection: GraphQLObjectType {

    /// Indicates if lane departure system incurred an error condition. True = Error. False = No Error.
    public var error: Bool? = nil

    /// Indicates if lane departure detection system is enabled. True = Enabled. False = Disabled.
    public var isActive: Bool? = nil

    /// Indicates if lane departure detection registered a lane departure
    public var warning: Bool? = nil
}