//
//  AngularVelocity.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct AngularVelocity: GraphQLType {

    /// Vehicle rotation rate along Y (lateral).
    public var pitch: Int? = nil

    /// Vehicle rotation rate along X (longitudinal).
    public var roll: Int? = nil

    /// Vehicle rotation rate along Z (vertical).
    public var yaw: Int? = nil
}