//
//  BodyWindshieldRear.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct BodyWindshieldRear: GraphQLType {

    public var heating: BodyWindshieldRearHeating? = nil

    public var washerFluid: BodyWindshieldRearWasherFluid? = nil

    public var wiping: BodyWindshieldRearWiping? = nil
}