//
//  BodyHorn.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct BodyHorn: GraphQLType {

    /// Horn active or inactive. True = Active. False = Inactive.
    public var isActive: Bool? = nil
}