//
//  BodyWindshieldFrontWiping.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct BodyWindshieldFrontWiping: GraphQLObjectType {

    /// Front wiper status
    public var status: BodyWindshieldFrontWipingStatus? = nil


    // MARK: GraphQLObjectType
    
    public static var scalars: [String : Any] {
        [
            "status" : BodyWindshieldFrontWipingStatus.self
        ]
    }
    
    public static var objects: [String : GraphQLObjectType.Type] {
        [:]
    }
}