//
//  BodyWindshieldFrontWasherFluid.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct BodyWindshieldFrontWasherFluid: GraphQLObjectType {

    /// Washer fluid level as a percent. 0 = Empty. 100 = Full.
    public var level: Int? = nil

    /// Low level indication for washer fluid. True = Level Low. False = Level OK.
    public var levelLow: Bool? = nil


    // MARK: GraphQLObjectType
    
    public static var scalars: [String : Any] {
        [
            "level" : Int.self,
            "levelLow" : Bool.self
        ]
    }
    
    public static var objects: [String : GraphQLObjectType.Type] {
        [:]
    }
}