//
//  BodyWindshieldFrontWasherFluid.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 15.05.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class BodyWindshieldFrontWasherFluid: Object, ObjectSchema {

    /// Washer fluid level as a percent. 0 = Empty. 100 = Full.
    public var level = Field<Int?, NoArguments>("level")

    /// Low level indication for washer fluid. True = Level Low. False = Level OK.
    public var levelLow = Field<Bool?, NoArguments>("levelLow")

    public required init() { }
}