//
//  BodyMirrors.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct BodyMirrors: GraphQLObjectType {

    public var `left`: BodyMirrorsLeft? = nil

    public var `right`: BodyMirrorsRight? = nil
}