//
//  BodyRaindetection.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct BodyRaindetection: GraphQLType {

    /// Rain intensity. 0 = Dry, No Rain. 100 = Covered.
    public var intensity: Int? = nil
}