//
//  BodyWindshieldRear.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct BodyWindshieldRear: GraphQLObjectType {

    public var heating: BodyWindshieldRearHeating? = nil

    public var washerFluid: BodyWindshieldRearWasherFluid? = nil

    public var wiping: BodyWindshieldRearWiping? = nil


    // MARK: GraphQLObjectType
    
    public static var scalars: [String : Any] {
        [:]
    }
    
    public static var objects: [String : GraphQLObjectType.Type] {
        [
            "heating" : BodyWindshieldRearHeating.self,
            "washerFluid" : BodyWindshieldRearWasherFluid.self,
            "wiping" : BodyWindshieldRearWiping.self
        ]
    }
}