//
//  BodyWindshieldRearWasherFluid.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct BodyWindshieldRearWasherFluid: GraphQLType {

    /// Washer fluid level as a percent. 0 = Empty. 100 = Full.
    public var level: Int? = nil

    /// Low level indication for washer fluid. True = Level Low. False = Level OK.
    public var levelLow: Bool? = nil
}