//
//  BodyWindshield.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct BodyWindshield: GraphQLObjectType {

    public var front: BodyWindshieldFront? = nil

    public var rear: BodyWindshieldRear? = nil
}