//
//  BodyRaindetection.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 25.05.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class BodyRaindetection: Object, ObjectSchema {

    /// Rain intensity. 0 = Dry, No Rain. 100 = Covered.
    public var intensity = Field<Int?, NoArguments>("intensity")

    public required init() { }
}