//
//  BodyWindshieldFront.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct BodyWindshieldFront: GraphQLObjectType {

    public var heating: BodyWindshieldFrontHeating? = nil

    public var washerFluid: BodyWindshieldFrontWasherFluid? = nil

    public var wiping: BodyWindshieldFrontWiping? = nil
}