//
//  BodyMirrorsRightHeating.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct BodyMirrorsRightHeating: GraphQLType {

    /// Mirror Heater on or off. True = Heater On. False = Heater Off.
    public var status: Bool? = nil
}