//
//  CabinLightsRow3.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 25.05.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class CabinLightsRow3: Object, ObjectSchema {

    /// Is light shared third across row on
    public var isSharedOn = Field<Bool?, NoArguments>("isSharedOn")

    public var `left` = Field<CabinLightsRow3Left?, NoArguments>("left")

    public var `right` = Field<CabinLightsRow3Right?, NoArguments>("right")

    public required init() { }
}