//
//  CabinSeatRow1Pos1SwitchLumbar.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinSeatRow1Pos1SwitchLumbar: GraphQLObjectType {

    /// Lumbar deflation switch engaged
    public var deflate: Bool? = nil

    /// Lumbar down switch engaged
    public var down: Bool? = nil

    /// Lumbar inflation switch engaged
    public var inflate: Bool? = nil

    /// Lumbar up switch engaged
    public var up: Bool? = nil
}