//
//  CabinDoorRow3.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinDoorRow3: GraphQLObjectType {

    public var `left`: CabinDoorRow3Left? = nil

    public var `right`: CabinDoorRow3Right? = nil


    // MARK: GraphQLObjectType
    
    public static var scalars: [String : Any] {
        [:]
    }
    
    public static var objects: [String : GraphQLObjectType.Type] {
        [
            "`left`" : CabinDoorRow3Left.self,
            "`right`" : CabinDoorRow3Right.self
        ]
    }
}