//
//  CabinLights.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinLights: GraphQLObjectType {

    /// How much ambient light is detected in cabin. 0 = No ambient light. 100 = Full brightness
    public var ambientLight: Int? = nil

    /// Is central dome light light on
    public var isDomeOn: Bool? = nil

    /// Is glove box light on
    public var isGloveBoxOn: Bool? = nil

    /// Is trunk light light on
    public var isTrunkOn: Bool? = nil

    /// Intensity of the interior lights. 0 = Off. 100 = Full brightness.
    public var lightIntensity: Int? = nil

    public var row1: CabinLightsRow1? = nil

    public var row2: CabinLightsRow2? = nil

    public var row3: CabinLightsRow3? = nil

    public var row4: CabinLightsRow4? = nil


    // MARK: GraphQLObjectType
    
    public static var scalars: [String : Any] {
        [
            "ambientLight" : Int.self,
            "isDomeOn" : Bool.self,
            "isGloveBoxOn" : Bool.self,
            "isTrunkOn" : Bool.self,
            "lightIntensity" : Int.self
        ]
    }
    
    public static var objects: [String : GraphQLObjectType.Type] {
        [
            "row1" : CabinLightsRow1.self,
            "row2" : CabinLightsRow2.self,
            "row3" : CabinLightsRow3.self,
            "row4" : CabinLightsRow4.self
        ]
    }
}