//
//  CabinSeatRow1Pos3.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinSeatRow1Pos3: GraphQLObjectType {

    public var airbag: CabinSeatRow1Pos3Airbag? = nil

    public var cushion: CabinSeatRow1Pos3Cushion? = nil

    /// Does the seat have a passenger in it.
    public var hasPassenger: Bool? = nil

    public var headRestraint: CabinSeatRow1Pos3HeadRestraint? = nil

    /// Seat cooling / heating. 0 = off. -100 = max cold. +100 = max heat
    public var heating: Int? = nil

    /// Is the belt engaged.
    public var isBelted: Bool? = nil

    public var lumbar: CabinSeatRow1Pos3Lumbar? = nil

    /// Seat massage level. 0 = off. 100 = max massage.
    public var massage: Int? = nil

    /// Seat horizontal position. 0 = Frontmost. 1000 = Rearmost
    public var position: Int? = nil

    /// Recline level. -90 = Max forward recline. 90 max backward recline
    public var recline: Int? = nil

    public var sideBolster: CabinSeatRow1Pos3SideBolster? = nil

    public var `switch`: CabinSeatRow1Pos3Switch? = nil


    // MARK: GraphQLObjectType
    
    public static var scalars: [String : Any] {
        [
            "hasPassenger" : Bool.self,
            "heating" : Int.self,
            "isBelted" : Bool.self,
            "massage" : Int.self,
            "position" : Int.self,
            "recline" : Int.self
        ]
    }
    
    public static var objects: [String : GraphQLObjectType.Type] {
        [
            "airbag" : CabinSeatRow1Pos3Airbag.self,
            "cushion" : CabinSeatRow1Pos3Cushion.self,
            "headRestraint" : CabinSeatRow1Pos3HeadRestraint.self,
            "lumbar" : CabinSeatRow1Pos3Lumbar.self,
            "sideBolster" : CabinSeatRow1Pos3SideBolster.self,
            "`switch`" : CabinSeatRow1Pos3Switch.self
        ]
    }
}