//
//  CabinInfotainmentNavigationDestinationSet.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinInfotainmentNavigationDestinationSet: GraphQLType {

    /// Latitude of destination
    public var latitude: Float? = nil

    /// Longitude of destination
    public var longitude: Float? = nil
}