//
//  CabinInfotainmentHMIDateFormat.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public enum CabinInfotainmentHMIDateFormat: String, GraphQLEnumType {

    case YYYYMmDd = "YYYY_MM_DD"

    case DDMmYyyy = "DD_MM_YYYY"

    case MMDdYyyy = "MM_DD_YYYY"

    case YYMmDd = "YY_MM_DD"

    case DDMmYy = "DD_MM_YY"

    case MMDdYy = "MM_DD_YY"
}