//
//  CabinLightsRow3.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinLightsRow3: GraphQLType {

    /// Is light shared third across row on
    public var isSharedOn: Bool? = nil

    public var `left`: CabinLightsRow3Left? = nil

    public var `right`: CabinLightsRow3Right? = nil
}