//
//  CabinInfotainmentHMIDistanceUnit.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.09.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum CabinInfotainmentHMIDistanceUnit: String, Enum {

    case mi = "mi"

    case km = "km"
}