//
//  CabinSeatRow4Pos5SideBolster.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinSeatRow4Pos5SideBolster: GraphQLObjectType {

    /// Lumbar support inflation. 0 = Fully deflated. 255 = Fully inflated.
    public var inflation: Int? = nil


    // MARK: GraphQLObjectType
    
    public static var scalars: [String : Any] {
        [
            "inflation" : Int.self
        ]
    }
    
    public static var objects: [String : GraphQLObjectType.Type] {
        [:]
    }
}