//
//  CabinSeatRow3Pos1SwitchHeadRestraint.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinSeatRow3Pos1SwitchHeadRestraint: GraphQLType {

    /// Head restraint down switch engaged
    public var down: Bool? = nil

    /// Head restraint up switch engaged
    public var up: Bool? = nil
}