//
//  CabinSeatRow3.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.09.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class CabinSeatRow3: Object, ObjectSchema {

    public var pos1 = Field<CabinSeatRow3Pos1?, NoArguments>("pos1")

    public var pos2 = Field<CabinSeatRow3Pos2?, NoArguments>("pos2")

    public var pos3 = Field<CabinSeatRow3Pos3?, NoArguments>("pos3")

    public var pos4 = Field<CabinSeatRow3Pos4?, NoArguments>("pos4")

    public var pos5 = Field<CabinSeatRow3Pos5?, NoArguments>("pos5")

    public required init() { }
}