//
//  CabinSunroofSwitch.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public enum CabinSunroofSwitch: String, GraphQLEnumType {

    case Inactive = "Inactive"

    case Close = "Close"

    case Open = "Open"

    case OneShotClose = "OneShotClose"

    case OneShotOpen = "OneShotOpen"

    case TiltUp = "TiltUp"

    case TiltDown = "TiltDown"
}