//
//  CabinRearviewMirror.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinRearviewMirror: GraphQLType {

    /// Dimming level of rearview mirror. 0 = undimmed. 100 = fully dimmed
    public var dimmingLevel: Int? = nil
}