//
//  CabinLightsRow3Left.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinLightsRow3Left: GraphQLType {

    /// Is passenger light on
    public var isPassengerOn: Bool? = nil
}