//
//  CabinSeatRow3Pos1HeadRestraint.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinSeatRow3Pos1HeadRestraint: GraphQLType {

    /// Height of head restraint. 0 = Bottommost. 255 = Topmost.
    public var height: Int? = nil
}