//
//  CabinHVACRow1.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinHVACRow1: GraphQLObjectType {

    public var `left`: CabinHVACRow1Left? = nil

    public var `right`: CabinHVACRow1Right? = nil


    // MARK: GraphQLObjectType
    
    public static var scalars: [String : Any] {
        [:]
    }
    
    public static var objects: [String : GraphQLObjectType.Type] {
        [
            "`left`" : CabinHVACRow1Left.self,
            "`right`" : CabinHVACRow1Right.self
        ]
    }
}