//
//  CabinSeatRow3Pos5Airbag.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinSeatRow3Pos5Airbag: GraphQLType {

    /// Airbag deployment status. True = Airbag deployed. False = Airbag not deployed.
    public var isDeployed: Bool? = nil
}