//
//  CabinInfotainmentNavigation.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinInfotainmentNavigation: GraphQLType {

    public var currentLocation: CabinInfotainmentNavigationCurrentLocation? = nil

    public var destinationSet: CabinInfotainmentNavigationDestinationSet? = nil
}