//
//  CabinSunroof.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 25.05.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class CabinSunroof: Object, ObjectSchema {

    /// Sunroof position. 0 = Fully closed 100 = Fully opened. -100 = Fully tilted
    public var position = Field<Int?, NoArguments>("position")

    public var shade = Field<CabinSunroofShade?, NoArguments>("shade")

    /// Switch controlling sliding action such as window, sunroof, or shade.
    public var `switch` = Field<CabinSunroofSwitch?, NoArguments>("switch")

    public required init() { }
}