//
//  CabinDoorRow1.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinDoorRow1: GraphQLObjectType {

    public var `left`: CabinDoorRow1Left? = nil

    public var `right`: CabinDoorRow1Right? = nil
}