//
//  CabinDoorRow2.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinDoorRow2: GraphQLType {

    public var `left`: CabinDoorRow2Left? = nil

    public var `right`: CabinDoorRow2Right? = nil
}