//
//  CabinInfotainmentNavigationDestinationSet.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.09.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class CabinInfotainmentNavigationDestinationSet: Object, ObjectSchema {

    /// Latitude of destination
    public var latitude = Field<Float?, NoArguments>("latitude")

    /// Longitude of destination
    public var longitude = Field<Float?, NoArguments>("longitude")

    public required init() { }
}