//
//  CabinSeatRow3Pos1Switch.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinSeatRow3Pos1Switch: GraphQLObjectType {

    /// Seat forward switch engaged
    public var backward: Bool? = nil

    /// Cooler switch for Seat heater
    public var cooler: Bool? = nil

    public var cushion: CabinSeatRow3Pos1SwitchCushion? = nil

    /// Seat down switch engaged
    public var down: Bool? = nil

    /// Seat forward switch engaged
    public var forward: Bool? = nil

    public var headRestraint: CabinSeatRow3Pos1SwitchHeadRestraint? = nil

    public var lumbar: CabinSeatRow3Pos1SwitchLumbar? = nil

    public var massage: CabinSeatRow3Pos1SwitchMassage? = nil

    public var recline: CabinSeatRow3Pos1SwitchRecline? = nil

    public var sideBolster: CabinSeatRow3Pos1SwitchSideBolster? = nil

    /// Seat up switch engaged
    public var up: Bool? = nil

    /// Warmer switch for Seat heater
    public var warmer: Bool? = nil


    // MARK: GraphQLObjectType
    
    public static var scalars: [String : Any] {
        [
            "backward" : Bool.self,
            "cooler" : Bool.self,
            "down" : Bool.self,
            "forward" : Bool.self,
            "up" : Bool.self,
            "warmer" : Bool.self
        ]
    }
    
    public static var objects: [String : GraphQLObjectType.Type] {
        [
            "cushion" : CabinSeatRow3Pos1SwitchCushion.self,
            "headRestraint" : CabinSeatRow3Pos1SwitchHeadRestraint.self,
            "lumbar" : CabinSeatRow3Pos1SwitchLumbar.self,
            "massage" : CabinSeatRow3Pos1SwitchMassage.self,
            "recline" : CabinSeatRow3Pos1SwitchRecline.self,
            "sideBolster" : CabinSeatRow3Pos1SwitchSideBolster.self
        ]
    }
}