//
//  Cabin.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct Cabin: GraphQLObjectType {

    public var convertible: CabinConvertible? = nil

    public var door: CabinDoor? = nil

    public var hvac: CabinHVAC? = nil

    public var infotainment: CabinInfotainment? = nil

    public var lights: CabinLights? = nil

    public var rearShade: CabinRearShade? = nil

    public var rearviewMirror: CabinRearviewMirror? = nil

    public var seat: CabinSeat? = nil

    public var steeringWheel: CabinSteeringWheel? = nil

    public var sunroof: CabinSunroof? = nil
}