//
//  CabinConvertible.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinConvertible: GraphQLType {

    /// Roof status on convertible vehicles
    public var status: CabinConvertibleStatus? = nil
}