//
//  CabinHVACRow3.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinHVACRow3: GraphQLObjectType {

    public var `left`: CabinHVACRow3Left? = nil

    public var `right`: CabinHVACRow3Right? = nil
}