//
//  CabinHVACRow4Left.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinHVACRow4Left: GraphQLType {

    /// Direction of airstream
    public var airDistribution: CabinHVACRow4LeftAirDistribution? = nil

    /// Fan Speed, 0 = off. 100 = max
    public var fanSpeed: Int? = nil

    /// Temperature
    public var temperature: Int? = nil
}