//
//  CabinLightsRow2.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinLightsRow2: GraphQLObjectType {

    /// Is light shared across second row on
    public var isSharedOn: Bool? = nil

    public var `left`: CabinLightsRow2Left? = nil

    public var `right`: CabinLightsRow2Right? = nil
}