//
//  CabinSteeringWheel.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinSteeringWheel: GraphQLObjectType {

    /// Position of the steering wheel inside the cabin
    public var position: CabinSteeringWheelPosition? = nil


    // MARK: GraphQLObjectType
    
    public static var scalars: [String : Any] {
        [
            "position" : CabinSteeringWheelPosition.self
        ]
    }
    
    public static var objects: [String : GraphQLObjectType.Type] {
        [:]
    }
}