//
//  CabinInfotainment.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinInfotainment: GraphQLObjectType {

    public var hmi: CabinInfotainmentHMI? = nil

    public var media: CabinInfotainmentMedia? = nil

    public var navigation: CabinInfotainmentNavigation? = nil


    // MARK: GraphQLObjectType
    
    public static var scalars: [String : Any] {
        [:]
    }
    
    public static var objects: [String : GraphQLObjectType.Type] {
        [
            "hmi" : CabinInfotainmentHMI.self,
            "media" : CabinInfotainmentMedia.self,
            "navigation" : CabinInfotainmentNavigation.self
        ]
    }
}