//
//  CabinLightsRow4Left.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinLightsRow4Left: GraphQLObjectType {

    /// Is passenger light on
    public var isPassengerOn: Bool? = nil
}