//
//  CabinDoorRow4.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 25.05.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class CabinDoorRow4: Object, ObjectSchema {

    public var `left` = Field<CabinDoorRow4Left?, NoArguments>("left")

    public var `right` = Field<CabinDoorRow4Right?, NoArguments>("right")

    public required init() { }
}