//
//  CabinSeatRow1Pos2Airbag.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinSeatRow1Pos2Airbag: GraphQLObjectType {

    /// Airbag deployment status. True = Airbag deployed. False = Airbag not deployed.
    public var isDeployed: Bool? = nil
}