//
//  CabinHVACRow1LeftAirDistribution.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public enum CabinHVACRow1LeftAirDistribution: String, GraphQLEnumType {

    case up = "up"

    case middle = "middle"

    case down = "down"
}