//
//  CabinDoorRow3LeftShadeSwitch.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public enum CabinDoorRow3LeftShadeSwitch: String, GraphQLType {

    case Inactive = "Inactive"

    case Close = "Close"

    case Open = "Open"

    case OneShotClose = "OneShotClose"

    case OneShotOpen = "OneShotOpen"
}