//
//  CabinConvertibleStatus.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public enum CabinConvertibleStatus: String, GraphQLEnumType {

    case undefined = "undefined"

    case closed = "closed"

    case open = "open"

    case closing = "closing"

    case opening = "opening"

    case stalled = "stalled"
}