//
//  CabinHVACRow4Left.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinHVACRow4Left: GraphQLObjectType {

    /// Direction of airstream
    public var airDistribution: CabinHVACRow4LeftAirDistribution? = nil

    /// Fan Speed, 0 = off. 100 = max
    public var fanSpeed: Int? = nil

    /// Temperature
    public var temperature: Int? = nil


    // MARK: GraphQLObjectType
    
    public static var scalars: [String : Any] {
        [
            "airDistribution" : CabinHVACRow4LeftAirDistribution.self,
            "fanSpeed" : Int.self,
            "temperature" : Int.self
        ]
    }
    
    public static var objects: [String : GraphQLObjectType.Type] {
        [:]
    }
}