//
//  CabinSeatRow1Pos4SwitchSideBolster.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinSeatRow1Pos4SwitchSideBolster: GraphQLObjectType {

    /// Lumbar deflation switch engaged
    public var deflate: Bool? = nil

    /// Lumbar inflation switch engaged
    public var inflate: Bool? = nil
}