//
//  CabinHVACRow4RightAirDistribution.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.09.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum CabinHVACRow4RightAirDistribution: String, Enum {

    case up = "up"

    case middle = "middle"

    case down = "down"
}