//
//  CabinHVACRow2Left.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct CabinHVACRow2Left: GraphQLObjectType {

    /// Direction of airstream
    public var airDistribution: CabinHVACRow2LeftAirDistribution? = nil

    /// Fan Speed, 0 = off. 100 = max
    public var fanSpeed: Int? = nil

    /// Temperature
    public var temperature: Int? = nil
}