//
//  CabinHVAC.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 15.05.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class CabinHVAC: Object, ObjectSchema {

    /// Ambient air temperature
    public var ambientAirTemperature = Field<Float?, NoArguments>("ambientAirTemperature")

    /// Is Air conditioning active.
    public var isAirConditioningActive = Field<Bool?, NoArguments>("isAirConditioningActive")

    /// Is front defroster active.
    public var isFrontDefrosterActive = Field<Bool?, NoArguments>("isFrontDefrosterActive")

    /// Is rear defroster active.
    public var isRearDefrosterActive = Field<Bool?, NoArguments>("isRearDefrosterActive")

    /// Is recirculation active.
    public var isRecirculationActive = Field<Bool?, NoArguments>("isRecirculationActive")

    public var row1 = Field<CabinHVACRow1?, NoArguments>("row1")

    public var row2 = Field<CabinHVACRow2?, NoArguments>("row2")

    public var row3 = Field<CabinHVACRow3?, NoArguments>("row3")

    public var row4 = Field<CabinHVACRow4?, NoArguments>("row4")

    public required init() { }
}