//
//  CabinInfotainmentHMIDayNightMode.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public enum CabinInfotainmentHMIDayNightMode: String, GraphQLEnumType {

    case Day = "Day"

    case Night = "Night"
}