//
//  ChassisParkingBrake.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct ChassisParkingBrake: GraphQLType {

    /// Parking brake status. True = Parking Brake is Engaged. False = Parking Brake is not Engaged.
    public var isEngaged: Bool? = nil
}