//
//  ChassisAxleRow1WheelRight.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct ChassisAxleRow1WheelRight: GraphQLType {

    public var brake: ChassisAxleRow1WheelRightBrake? = nil

    public var tire: ChassisAxleRow1WheelRightTire? = nil
}