//
//  ChassisAxleRow2WheelRight.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct ChassisAxleRow2WheelRight: GraphQLObjectType {

    public var brake: ChassisAxleRow2WheelRightBrake? = nil

    public var tire: ChassisAxleRow2WheelRightTire? = nil


    // MARK: GraphQLObjectType
    
    public static var scalars: [String : Any] {
        [:]
    }
    
    public static var objects: [String : GraphQLObjectType.Type] {
        [
            "brake" : ChassisAxleRow2WheelRightBrake.self,
            "tire" : ChassisAxleRow2WheelRightTire.self
        ]
    }
}