//
//  ChassisTrailer.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct ChassisTrailer: GraphQLType {

    /// Signal indicating if trailer is connected or not.
    public var connected: Bool? = nil
}