//
//  ChassisAxleRow1WheelRightTire.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct ChassisAxleRow1WheelRightTire: GraphQLObjectType {

    /// Tire pressure in kilo-Pascal
    public var pressure: Int? = nil

    /// Tire Pressure Status. True = Low tire pressure. False = Good tire pressure.
    public var pressureLow: Bool? = nil

    /// Tire temperature in Celsius.
    public var temperature: Float? = nil


    // MARK: GraphQLObjectType
    
    public static var scalars: [String : Any] {
        [
            "pressure" : Int.self,
            "pressureLow" : Bool.self,
            "temperature" : Float.self
        ]
    }
    
    public static var objects: [String : GraphQLObjectType.Type] {
        [:]
    }
}