//
//  DrivetrainBatteryManagementChargingInlet.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public enum DrivetrainBatteryManagementChargingInlet: String, GraphQLEnumType {

    case unknown = "unknown"

    case NotFitted = "Not_Fitted"

    case ACType1 = "AC_Type_1"

    case ACType2 = "AC_Type_2"

    case ACGbt = "AC_GBT"

    case ACDcType1Combo = "AC_DC_Type_1_Combo"

    case ACDcType2Combo = "AC_DC_Type_2_Combo"

    case DCGbt = "DC_GBT"

    case DCChademo = "DC_Chademo"
}