//
//  DrivetrainBatteryManagementStateOfCharge.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.09.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class DrivetrainBatteryManagementStateOfCharge: Object, ObjectSchema {

    /// Physical state of charge of the high voltage battery. This is not necessarily the state of charge being displayed to the customer (as a percentage between 0.0% - 100.0%)
    public var current = Field<Float?, NoArguments>("current")

    /// State of charge displayed to the customer (as a percentage between 0.0% - 100.0%)
    public var displayed = Field<Float?, NoArguments>("displayed")

    /// Target state of charge set (eg. by customer; as a percentage between 0% - 100%)
    public var target = Field<Int?, NoArguments>("target")

    public required init() { }
}