//
//  DrivetrainTransmission.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct DrivetrainTransmission: GraphQLObjectType {

    /// Clutch wear as a percent. 0 = no wear. 100 = worn.
    public var clutchWear: Int? = nil

    /// Drive type.
    public var driveType: DrivetrainTransmissionDriveType? = nil

    /// Current gear. 0=Neutral. -1=Reverse
    public var gear: Int? = nil

    /// Is the gearbox in automatic or manual (paddle) mode.
    public var gearChangeMode: DrivetrainTransmissionGearChangeMode? = nil

    /// Number of forward gears in the transmission. -1 = CVT.
    public var gearCount: Int? = nil

    /// Current gearbox performance mode.
    public var performanceMode: DrivetrainTransmissionPerformanceMode? = nil

    /// Vehicle speed, as sensed by the gearbox.
    public var speed: Float? = nil

    /// The current gearbox temperature
    public var temperature: Int? = nil

    /// Odometer reading
    public var travelledDistance: Float? = nil

    /// Transmission type.
    public var type: DrivetrainTransmissionType? = nil


    // MARK: GraphQLObjectType
    
    public static var scalars: [String : Any] {
        [
            "clutchWear" : Int.self,
            "driveType" : DrivetrainTransmissionDriveType.self,
            "gear" : Int.self,
            "gearChangeMode" : DrivetrainTransmissionGearChangeMode.self,
            "gearCount" : Int.self,
            "performanceMode" : DrivetrainTransmissionPerformanceMode.self,
            "speed" : Float.self,
            "temperature" : Int.self,
            "travelledDistance" : Float.self,
            "type" : DrivetrainTransmissionType.self
        ]
    }
    
    public static var objects: [String : GraphQLObjectType.Type] {
        [:]
    }
}