//
//  DrivetrainTransmissionPerformanceMode.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public enum DrivetrainTransmissionPerformanceMode: String, GraphQLEnumType {

    case normal = "normal"

    case sport = "sport"

    case economy = "economy"

    case snow = "snow"

    case rain = "rain"
}