//
//  Drivetrain.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct Drivetrain: GraphQLObjectType {

    public var batteryManagement: DrivetrainBatteryManagement? = nil

    public var electricMotor: DrivetrainElectricMotor? = nil

    public var fuelCell: DrivetrainFuelCell? = nil

    public var fuelSystem: DrivetrainFuelSystem? = nil

    public var internalCombustionEngine: DrivetrainInternalCombustionEngine? = nil

    public var transmission: DrivetrainTransmission? = nil


    // MARK: GraphQLObjectType
    
    public static var scalars: [String : Any] {
        [:]
    }
    
    public static var objects: [String : GraphQLObjectType.Type] {
        [
            "batteryManagement" : DrivetrainBatteryManagement.self,
            "electricMotor" : DrivetrainElectricMotor.self,
            "fuelCell" : DrivetrainFuelCell.self,
            "fuelSystem" : DrivetrainFuelSystem.self,
            "internalCombustionEngine" : DrivetrainInternalCombustionEngine.self,
            "transmission" : DrivetrainTransmission.self
        ]
    }
}