//
//  DrivetrainInternalCombustionEngineConfiguration.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public enum DrivetrainInternalCombustionEngineConfiguration: String, GraphQLType {

    case unknown = "unknown"

    case straight = "straight"

    case V = "V"

    case boxer = "boxer"

    case W = "W"

    case rotary = "rotary"

    case radial = "radial"

    case square = "square"

    case H = "H"

    case U = "U"

    case opposed = "opposed"

    case X = "X"
}