//
//  DrivetrainFuelSystemHybridType.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public enum DrivetrainFuelSystemHybridType: String, GraphQLType {

    case unknown = "unknown"

    case notApplicable = "not_applicable"

    case stopStart = "stop_start"

    case beltIsg = "belt_ISG"

    case CIMG = "CIMG"

    case PHEV = "PHEV"
}