//
//  DrivetrainTransmissionDriveType.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public enum DrivetrainTransmissionDriveType: String, GraphQLType {

    case unknown = "unknown"

    case forwardWheelDrive = "forward_wheel_drive"

    case rearWheelDrive = "rear_wheel_drive"

    case allWheelDrive = "all_wheel_drive"
}