//
//  DrivetrainTransmissionPerformanceMode.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 25.05.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum DrivetrainTransmissionPerformanceMode: String, Enum {

    case normal = "normal"

    case sport = "sport"

    case economy = "economy"

    case snow = "snow"

    case rain = "rain"
}