//
//  DrivetrainInternalCombustionEngineEngine.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct DrivetrainInternalCombustionEngineEngine: GraphQLObjectType {

    /// Ambient (Outside) air temperature
    public var ambientAirTemperature: Float? = nil

    /// Engine coolant temperature.
    public var ect: Int? = nil

    /// Engine oil pressure.
    public var eop: Int? = nil

    /// Engine oil temperature.
    public var eot: Int? = nil

    /// Grams of air drawn into engine per second.
    public var maf: Int? = nil

    /// Manifold air pressure possibly boosted using forced induction.
    public var map: Int? = nil

    /// Current engine power output.
    public var power: Int? = nil

    /// Engine speed measured as rotations per minute.
    public var speed: Int? = nil

    /// Current throttle position.
    public var tps: Int? = nil

    /// Current engine torque.
    public var torque: Int? = nil


    // MARK: GraphQLObjectType
    
    public static var scalars: [String : Any] {
        [
            "ambientAirTemperature" : Float.self,
            "ect" : Int.self,
            "eop" : Int.self,
            "eot" : Int.self,
            "maf" : Int.self,
            "map" : Int.self,
            "power" : Int.self,
            "speed" : Int.self,
            "tps" : Int.self,
            "torque" : Int.self
        ]
    }
    
    public static var objects: [String : GraphQLObjectType.Type] {
        [:]
    }
}