//
//  DrivetrainInternalCombustionEngineFuelType.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public enum DrivetrainInternalCombustionEngineFuelType: String, GraphQLType {

    case unknown = "unknown"

    case gasoline = "gasoline"

    case diesel = "diesel"

    case E85 = "E85"

    case CNG = "CNG"
}