//
//  DrivetrainTransmissionType.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.09.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum DrivetrainTransmissionType: String, Enum {

    case unknown = "unknown"

    case sequential = "sequential"

    case H = "H"

    case automatic = "automatic"

    case DSG = "DSG"

    case CVT = "CVT"
}