//
//  DrivetrainFuelSystemFuelType.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public enum DrivetrainFuelSystemFuelType: String, GraphQLEnumType {

    case unknown = "unknown"

    case gasoline = "gasoline"

    case diesel = "diesel"

    case electric = "electric"

    case hybrid = "hybrid"

    case E85 = "E85"

    case CNG = "CNG"

    case LPG = "LPG"
}