//
//  Drivetrain.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct Drivetrain: GraphQLType {

    public var batteryManagement: DrivetrainBatteryManagement? = nil

    public var electricMotor: DrivetrainElectricMotor? = nil

    public var fuelCell: DrivetrainFuelCell? = nil

    public var fuelSystem: DrivetrainFuelSystem? = nil

    public var internalCombustionEngine: DrivetrainInternalCombustionEngine? = nil

    public var transmission: DrivetrainTransmission? = nil
}