//
//  OBDCatalystBank2.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct OBDCatalystBank2: GraphQLObjectType {

    /// PID 3D - Catalyst temperature from bank 2, sensor 1
    public var temperature1: Float? = nil

    /// PID 3F - Catalyst temperature from bank 2, sensor 2
    public var temperature2: Float? = nil


    // MARK: GraphQLObjectType
    
    public static var scalars: [String : Any] {
        [
            "temperature1" : Float.self,
            "temperature2" : Float.self
        ]
    }
    
    public static var objects: [String : GraphQLObjectType.Type] {
        [:]
    }
}