//
//  OBDCatalystBank1.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct OBDCatalystBank1: GraphQLType {

    /// PID 3C - Catalyst temperature from bank 1, sensor 1
    public var temperature1: Float? = nil

    /// PID 3E - Catalyst temperature from bank 1, sensor 2
    public var temperature2: Float? = nil
}