//
//  OBDCatalyst.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.09.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class OBDCatalyst: Object, ObjectSchema {

    public var bank1 = Field<OBDCatalystBank1?, NoArguments>("bank1")

    public var bank2 = Field<OBDCatalystBank2?, NoArguments>("bank2")

    public required init() { }
}