//
//  OBDCatalyst.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct OBDCatalyst: GraphQLType {

    public var bank1: OBDCatalystBank1? = nil

    public var bank2: OBDCatalystBank2? = nil
}