//
//  OBDDriveCycleStatusIgnitionType.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public enum OBDDriveCycleStatusIgnitionType: String, GraphQLEnumType {

    case spark = "spark"

    case compression = "compression"
}