//
//  OBDDriveCycleStatus.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct OBDDriveCycleStatus: GraphQLType {

    /// Number of sensor Trouble Codes (DTC)
    public var dtcCount: Float? = nil

    /// Type of the ignition for ICE - spark = spark plug ignition, compression = self-igniting (Diesel engines)
    public var ignitionType: OBDDriveCycleStatusIgnitionType? = nil

    /// Malfunction Indicator Light (MIL) - False = Off, True = On
    public var mil: Bool? = nil
}