//
//  OBDDriveCycleStatusIgnitionType.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 25.05.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum OBDDriveCycleStatusIgnitionType: String, Enum {

    case spark = "spark"

    case compression = "compression"
}