//
//  OBDO2WRSensor5.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct OBDO2WRSensor5: GraphQLType {

    /// PID 38 - Lambda current for wide range/band oxygen sensor 5
    public var current: Float? = nil

    /// PID 28 - Lambda voltage for wide range/band oxygen sensor 5
    public var voltage: Float? = nil
}