//
//  OBDO2AltBank1.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 15.05.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class OBDO2AltBank1: Object, ObjectSchema {

    public var sensor1 = Field<OBDO2AltBank1Sensor1?, NoArguments>("sensor1")

    public var sensor2 = Field<OBDO2AltBank1Sensor2?, NoArguments>("sensor2")

    public var sensor3 = Field<OBDO2AltBank1Sensor3?, NoArguments>("sensor3")

    public var sensor4 = Field<OBDO2AltBank1Sensor4?, NoArguments>("sensor4")

    public required init() { }
}