//
//  OBDO2AltBank1Sensor3.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct OBDO2AltBank1Sensor3: GraphQLType {

    /// Dummy description
    public var dummyField: String? = nil
}