//
//  OBDO2.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct OBDO2: GraphQLType {

    public var bank1: OBDO2Bank1? = nil

    public var bank2: OBDO2Bank2? = nil
}