//
//  OBDO2Bank1.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct OBDO2Bank1: GraphQLType {

    public var sensor1: OBDO2Bank1Sensor1? = nil

    public var sensor2: OBDO2Bank1Sensor2? = nil

    public var sensor3: OBDO2Bank1Sensor3? = nil

    public var sensor4: OBDO2Bank1Sensor4? = nil
}