//
//  OBDO2Alt.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct OBDO2Alt: GraphQLObjectType {

    public var bank1: OBDO2AltBank1? = nil

    public var bank2: OBDO2AltBank2? = nil
}