//
//  OBDO2WRSensor3.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct OBDO2WRSensor3: GraphQLObjectType {

    /// PID 36 - Lambda current for wide range/band oxygen sensor 4
    public var current: Float? = nil

    /// PID 26 - Lambda voltage for wide range/band oxygen sensor 3
    public var voltage: Float? = nil
}