//
//  OBDO2AltBank1Sensor3.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.09.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class OBDO2AltBank1Sensor3: Object, ObjectSchema {

    /// Dummy description
    public var dummyField = Field<String?, NoArguments>("dummyField")

    public required init() { }
}