//
//  OBDO2Bank2Sensor2.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct OBDO2Bank2Sensor2: GraphQLType {

    /// PID 19 - Sensor voltage
    public var voltage: Float? = nil
}