//
//  OBDO2Bank1Sensor4.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct OBDO2Bank1Sensor4: GraphQLObjectType {

    /// PID 17 - Sensor voltage
    public var voltage: Float? = nil
}