//
//  OBDO2AltBank1.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct OBDO2AltBank1: GraphQLObjectType {

    public var sensor1: OBDO2AltBank1Sensor1? = nil

    public var sensor2: OBDO2AltBank1Sensor2? = nil

    public var sensor3: OBDO2AltBank1Sensor3? = nil

    public var sensor4: OBDO2AltBank1Sensor4? = nil


    // MARK: GraphQLObjectType
    
    public static var scalars: [String : Any] {
        [:]
    }
    
    public static var objects: [String : GraphQLObjectType.Type] {
        [
            "sensor1" : OBDO2AltBank1Sensor1.self,
            "sensor2" : OBDO2AltBank1Sensor2.self,
            "sensor3" : OBDO2AltBank1Sensor3.self,
            "sensor4" : OBDO2AltBank1Sensor4.self
        ]
    }
}