//
//  OBDO2WRSensor4.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 14.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct OBDO2WRSensor4: GraphQLType {

    /// PID 37 - Lambda current for wide range/band oxygen sensor 4
    public var current: Float? = nil

    /// PID 27 - Lambda voltage for wide range/band oxygen sensor 4
    public var voltage: Float? = nil
}