//
//  OBDStatus.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 21.10.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Foundation


public struct OBDStatus: GraphQLObjectType {

    /// Number of sensor Trouble Codes (DTC)
    public var dtcCount: Float? = nil

    /// Type of the ignition for ICE - spark = spark plug ignition, compression = self-igniting (Diesel engines)
    public var ignitionType: OBDStatusIgnitionType? = nil

    /// Malfunction Indicator Light (MIL) False = Off, True = On
    public var mil: Bool? = nil


    // MARK: GraphQLObjectType
    
    public static var scalars: [String : Any] {
        [
            "dtcCount" : Float.self,
            "ignitionType" : OBDStatusIgnitionType.self,
            "mil" : Bool.self
        ]
    }
    
    public static var objects: [String : GraphQLObjectType.Type] {
        [:]
    }
}