import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Cabin_Seat_Row1_Pos1_Switch_SideBolster {
     """
     Lumbar deflation switch engaged
     """
     deflate: Boolean
     """
     Lumbar inflation switch engaged
     """
     inflate: Boolean
   }
*/

final class Vehicle_Cabin_Seat_Switch_SideBolster: Object, ObjectSchema {

   /**
    Lumbar deflation switch engaged
   */
   var deflate = Field<Bool?, NoArguments>("deflate")

   /**
    Lumbar inflation switch engaged
   */
   var inflate = Field<Bool?, NoArguments>("inflate")
}
