import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Cabin_Seat_Row1_Pos1_Switch_Recline {
     """
     Seatback recline backward switch engaged
     """
     backward: Boolean
     """
     Seatback recline forward switch engaged
     """
     forward: Boolean
   }
*/

final class Vehicle_Cabin_Seat_Switch_Recline: Object, ObjectSchema {

   /**
    Seatback recline backward switch engaged
   */
   var backward = Field<Bool?, NoArguments>("backward")

   /**
    Seatback recline forward switch engaged
   */
   var forward = Field<Bool?, NoArguments>("forward")
}
