import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Cabin_Seat_Row1_Pos1_Airbag {
     """
     Airbag deployment status. True = Airbag deployed. False = Airbag not deployed.
     """
     isDeployed: Boolean
   }
*/

final class Vehicle_Cabin_Seat_Airbag: Object, ObjectSchema {

   /**
    Airbag deployment status. True = Airbag deployed. False = Airbag not deployed.
   */
   var isDeployed = Field<Bool?, NoArguments>("isDeployed")
}
