import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Cabin_Seat {
     """
     The position of the driver seat in row 1. (1-5)
     """
     driverPosition: Int
     row1: Vehicle_Cabin_Seat_Row1
     """
     Number of seats across row 1 (frontmost)
     """
     row1PosCount: Int
     row2: Vehicle_Cabin_Seat_Row2
     """
     Number of seats across row 2
     """
     row2PosCount: Int
     row3: Vehicle_Cabin_Seat_Row3
     """
     Number of seats across row 3
     """
     row3PosCount: Int
     row4: Vehicle_Cabin_Seat_Row4
     """
     Number of seats across row 4
     """
     row4PosCount: Int
     """
     Number of seats across row 5
     """
     row5PosCount: Int
     """
     Number of seat rows in vehicle
     """
     rowCount: Int
   }
*/

final class Vehicle_Cabin_Seats: Object, ObjectSchema {

   /**
    The position of the driver seat in row 1. (1-5)
   */
   var driverPosition = Field<Int?, NoArguments>("driverPosition")

   var row1 = Field<Vehicle_Cabin_Seat_Row?, NoArguments>("row1")

   /**
    Number of seats across row 1 (frontmost)
   */
   var row1PosCount = Field<Int?, NoArguments>("row1PosCount")

   var row2 = Field<Vehicle_Cabin_Seat_Row?, NoArguments>("row2")

   /**
    Number of seats across row 2
   */
   var row2PosCount = Field<Int?, NoArguments>("row2PosCount")

   var row3 = Field<Vehicle_Cabin_Seat_Row?, NoArguments>("row3")

   /**
    Number of seats across row 3
   */
   var row3PosCount = Field<Int?, NoArguments>("row3PosCount")

   var row4 = Field<Vehicle_Cabin_Seat_Row?, NoArguments>("row4")

   /**
    Number of seats across row 4
   */
   var row4PosCount = Field<Int?, NoArguments>("row4PosCount")

   /**
    Number of seats across row 5
   */
   var row5PosCount = Field<Int?, NoArguments>("row5PosCount")

   /**
    Number of seat rows in vehicle
   */
   var rowCount = Field<Int?, NoArguments>("rowCount")
}
