import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Cabin_Seat_Row4_Pos1_Switch {
     """
     Seat forward switch engaged
     """
     backward: Boolean
     """
     Cooler switch for Seat heater
     """
     cooler: Boolean
     cushion: Vehicle_Cabin_Seat_Row4_Pos1_Switch_Cushion
     """
     Seat down switch engaged
     """
     down: Boolean
     """
     Seat forward switch engaged
     """
     forward: Boolean
     headRestraint: Vehicle_Cabin_Seat_Row4_Pos1_Switch_HeadRestraint
     lumbar: Vehicle_Cabin_Seat_Row4_Pos1_Switch_Lumbar
     massage: Vehicle_Cabin_Seat_Row4_Pos1_Switch_Massage
     recline: Vehicle_Cabin_Seat_Row4_Pos1_Switch_Recline
     sideBolster: Vehicle_Cabin_Seat_Row4_Pos1_Switch_SideBolster
     """
     Seat up switch engaged
     """
     up: Boolean
     """
     Warmer switch for Seat heater
     """
     warmer: Boolean
   }
*/

final class Vehicle_Cabin_Seat_Switch: Object, ObjectSchema {

   /**
    Seat forward switch engaged
   */
   var backward = Field<Bool?, NoArguments>("backward")

   /**
    Cooler switch for Seat heater
   */
   var cooler = Field<Bool?, NoArguments>("cooler")

   var cushion = Field<Vehicle_Cabin_Seat_Switch_Cushion?, NoArguments>("cushion")

   /**
    Seat down switch engaged
   */
   var down = Field<Bool?, NoArguments>("down")

   /**
    Seat forward switch engaged
   */
   var forward = Field<Bool?, NoArguments>("forward")

   var headRestraint = Field<Vehicle_Cabin_Seat_Switch_HeadRestraint?, NoArguments>("headRestraint")

   var lumbar = Field<Vehicle_Cabin_Seat_Switch_Lumbar?, NoArguments>("lumbar")

   var massage = Field<Vehicle_Cabin_Seat_Switch_Massage?, NoArguments>("massage")

   var recline = Field<Vehicle_Cabin_Seat_Switch_Recline?, NoArguments>("recline")

   var sideBolster = Field<Vehicle_Cabin_Seat_Switch_SideBolster?, NoArguments>("sideBolster")

   /**
    Seat up switch engaged
   */
   var up = Field<Bool?, NoArguments>("up")

   /**
    Warmer switch for Seat heater
   */
   var warmer = Field<Bool?, NoArguments>("warmer")
}
