import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Cabin_Seat_Row1_Pos1_Switch_HeadRestraint {
     """
     Head restraint down switch engaged
     """
     down: Boolean
     """
     Head restraint up switch engaged
     """
     up: Boolean
   }
*/

final class Vehicle_Cabin_Seat_Switch_HeadRestraint: Object, ObjectSchema {

   /**
    Head restraint down switch engaged
   */
   var down = Field<Bool?, NoArguments>("down")

   /**
    Head restraint up switch engaged
   */
   var up = Field<Bool?, NoArguments>("up")
}
