import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Cabin_Seat_Row1_Pos1_Cushion {
     """
     Height of the seat front. 0 = Lowermost. 500 = Uppermost.
     """
     height: Int
     """
     Forward length of cushion (leg support). 0 = Rearmost. 500 = Forwardmost.
     """
     length: Int
   }
*/

final class Vehicle_Cabin_Seat_Cushion: Object, ObjectSchema {

   /**
    Height of the seat front. 0 = Lowermost. 500 = Uppermost.
   */
   var height = Field<Int?, NoArguments>("height")

   /**
    Forward length of cushion (leg support). 0 = Rearmost. 500 = Forwardmost.
   */
   var length = Field<Int?, NoArguments>("length")
}
