import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_OBD_O2_Bank1 {
     sensor1: Vehicle_OBD_O2_Bank1_Sensor1
     sensor2: Vehicle_OBD_O2_Bank1_Sensor2
     sensor3: Vehicle_OBD_O2_Bank1_Sensor3
     sensor4: Vehicle_OBD_O2_Bank1_Sensor4
   }
*/

final class Vehicle_OBD_O2_Bank1: Object, ObjectSchema {

    /**
     PID 14 - Sensor voltage
     */
    var sensor1 = Field<Vehicle_OBD_O2_Sensor?, NoArguments>("sensor1")

    /**
     PID 15 - Sensor voltage
     */
    var sensor2 = Field<Vehicle_OBD_O2_Sensor?, NoArguments>("sensor2")

    /**
     PID 16 - Sensor voltage
     */
    var sensor3 = Field<Vehicle_OBD_O2_Sensor?, NoArguments>("sensor3")

    /**
     PID 17 - Sensor voltage
     */
    var sensor4 = Field<Vehicle_OBD_O2_Sensor?, NoArguments>("sensor4")
}
