import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_OBD_O2WR {
     sensor1: Vehicle_OBD_O2WR_Sensor1
     sensor2: Vehicle_OBD_O2WR_Sensor2
     sensor3: Vehicle_OBD_O2WR_Sensor3
     sensor4: Vehicle_OBD_O2WR_Sensor4
     sensor5: Vehicle_OBD_O2WR_Sensor5
     sensor6: Vehicle_OBD_O2WR_Sensor6
     sensor7: Vehicle_OBD_O2WR_Sensor7
     sensor8: Vehicle_OBD_O2WR_Sensor8
   }
*/

final class Vehicle_OBD_O2WR: Object, ObjectSchema {

    /**
     PID 34 - Lambda current for wide range/band oxygen sensor 1
     PID 24 - Lambda voltage for wide range/band oxygen sensor 1
     */
    var sensor1 = Field<Vehicle_OBD_O2WR_Sensor?, NoArguments>("sensor1")

    /**
     PID 35 - Lambda current for wide range/band oxygen sensor 2
     PID 25 - Lambda voltage for wide range/band oxygen sensor 2
     */
    var sensor2 = Field<Vehicle_OBD_O2WR_Sensor?, NoArguments>("sensor2")

    /**
     PID 36 - Lambda current for wide range/band oxygen sensor 4
     PID 26 - Lambda voltage for wide range/band oxygen sensor 3
     */
    var sensor3 = Field<Vehicle_OBD_O2WR_Sensor?, NoArguments>("sensor3")

    /**
     PID 37 - Lambda current for wide range/band oxygen sensor 4
     PID 27 - Lambda voltage for wide range/band oxygen sensor 4
     */
    var sensor4 = Field<Vehicle_OBD_O2WR_Sensor?, NoArguments>("sensor4")

    /**
     PID 38 - Lambda current for wide range/band oxygen sensor 5
     PID 28 - Lambda voltage for wide range/band oxygen sensor 5
     */
    var sensor5 = Field<Vehicle_OBD_O2WR_Sensor?, NoArguments>("sensor5")

    /**
     PID 39 - Lambda current for wide range/band oxygen sensor 6
     PID 29 - Lambda voltage for wide range/band oxygen sensor 6
     */
    var sensor6 = Field<Vehicle_OBD_O2WR_Sensor?, NoArguments>("sensor6")

    /**
     PID 3A - Lambda current for wide range/band oxygen sensor 7
     PID 2A - Lambda voltage for wide range/band oxygen sensor 7
     */
    var sensor7 = Field<Vehicle_OBD_O2WR_Sensor?, NoArguments>("sensor7")

    /**
     PID 3B - Lambda current for wide range/band oxygen sensor 8
     PID 2B - Lambda voltage for wide range/band oxygen sensor 8
     */
    var sensor8 = Field<Vehicle_OBD_O2WR_Sensor?, NoArguments>("sensor8")
}
