import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_OBD_O2_Bank1_Sensor1 {
     """
     PID 14 - Sensor voltage
     """
     voltage: Float
   }
*/

final class Vehicle_OBD_O2_Sensor: Object, ObjectSchema {

   /**
    PID 14 - Sensor voltage
   */
   var voltage = Field<Float?, NoArguments>("voltage")
}
