import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   enum Vehicle_OBD_DriveCycleStatus_IgnitionType_Enum {
     spark
     compression
   }
*/

enum Vehicle_OBD_DriveCycleStatus_IgnitionType_Enum: String, Enum {
   case spark = "spark"
   case compression = "compression"
}
