import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Cabin {
     convertible: Vehicle_Cabin_Convertible
     door: Vehicle_Cabin_Door
     hvac: Vehicle_Cabin_HVAC
     infotainment: Vehicle_Cabin_Infotainment
     lights: Vehicle_Cabin_Lights
     rearShade: Vehicle_Cabin_RearShade
     rearviewMirror: Vehicle_Cabin_RearviewMirror
     seat: Vehicle_Cabin_Seat
     steeringWheel: Vehicle_Cabin_SteeringWheel
     sunroof: Vehicle_Cabin_Sunroof
   }
*/

final class Vehicle_Cabin: Object, ObjectSchema {

   var convertible = Field<Vehicle_Cabin_Convertible?, NoArguments>("convertible")

   var doors = Field<Vehicle_Cabin_Doors?, NoArguments>("door")

   var hvac = Field<Vehicle_Cabin_HVAC?, NoArguments>("hvac")

   var infotainment = Field<Vehicle_Cabin_Infotainment?, NoArguments>("infotainment")

   var lights = Field<Vehicle_Cabin_Lights?, NoArguments>("lights")

   var rearShade = Field<Vehicle_Cabin_RearShade?, NoArguments>("rearShade")

   var rearviewMirror = Field<Vehicle_Cabin_RearviewMirror?, NoArguments>("rearviewMirror")

   var seat = Field<Vehicle_Cabin_Seats?, NoArguments>("seat")

   var steeringWheel = Field<Vehicle_Cabin_SteeringWheel?, NoArguments>("steeringWheel")

   var sunroof = Field<Vehicle_Cabin_Sunroof?, NoArguments>("sunroof")
}
