import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Chassis_Axle {
     """
     Number of axles on the vehicle
     """
     count: Int
     row1: Vehicle_Chassis_Axle_Row1
     row2: Vehicle_Chassis_Axle_Row2
   }
*/

final class Vehicle_Chassis_Axle: Object, ObjectSchema {

   /**
    Number of axles on the vehicle
   */
   var count = Field<Int?, NoArguments>("count")

   var row1 = Field<Vehicle_Chassis_Axle_Row?, NoArguments>("row1")

   var row2 = Field<Vehicle_Chassis_Axle_Row?, NoArguments>("row2")
}
