import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Chassis_Axle_Row1_Wheel {
     left: Vehicle_Chassis_Axle_Row1_Wheel_Left
     right: Vehicle_Chassis_Axle_Row1_Wheel_Right
   }
*/

final class Vehicle_Chassis_Axle_Wheels: Object, ObjectSchema {

   var left = Field<Vehicle_Chassis_Axle_Wheel?, NoArguments>("left")

   var right = Field<Vehicle_Chassis_Axle_Wheel?, NoArguments>("right")
}
