import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Chassis_Axle_Row1_Wheel_Left_Tire {
     """
     Tire pressure in kilo-Pascal
     """
     pressure: Int
     """
     Tire Pressure Status. True = Low tire pressure. False = Good tire pressure.
     """
     pressureLow: Boolean
     """
     Tire temperature in Celsius.
     """
     temperature: Float
   }
*/

final class Vehicle_Chassis_Axle_Wheel_Tire: Object, ObjectSchema {

   /**
    Tire pressure in kilo-Pascal
   */
   var pressure = Field<Int?, NoArguments>("pressure")

   /**
    Tire Pressure Status. True = Low tire pressure. False = Good tire pressure.
   */
   var pressureLow = Field<Bool?, NoArguments>("pressureLow")

   /**
    Tire temperature in Celsius.
   */
   var temperature = Field<Float?, NoArguments>("temperature")
}
