import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Chassis {
     accelerator: Vehicle_Chassis_Accelerator
     axle: Vehicle_Chassis_Axle
     brake: Vehicle_Chassis_Brake
     """
     Vehicle curb weight, in kg, including all liquids and full tank of fuel, but no cargo or passengers.
     """
     curbWeight: Int
     """
     Curb weight of vehicle, including all liquids and full tank of fuel and full load of cargo and passengers.
     """
     grossWeight: Int
     """
     Overall vehicle height, in mm.
     """
     height: Int
     """
     Overall vehicle length, in mm.
     """
     length: Int
     parkingBrake: Vehicle_Chassis_ParkingBrake
     steeringWheel: Vehicle_Chassis_SteeringWheel
     """
     Maximum weight, in kilos, of trailer.
     """
     towWeight: Int
     """
     Overall wheel tracking, in mm.
     """
     track: Int
     trailer: Vehicle_Chassis_Trailer
     """
     Overall wheel base, in mm.
     """
     wheelbase: Int
     """
     Overall vehicle width, in mm.
     """
     width: Int
   }
*/

final class Vehicle_Chassis: Object, ObjectSchema {

   var accelerator = Field<Vehicle_Chassis_Accelerator?, NoArguments>("accelerator")

   var axle = Field<Vehicle_Chassis_Axle?, NoArguments>("axle")

   var brake = Field<Vehicle_Chassis_Brake?, NoArguments>("brake")

   /**
    Vehicle curb weight, in kg, including all liquids and full tank of fuel, but no cargo or passengers.
   */
   var curbWeight = Field<Int?, NoArguments>("curbWeight")

   /**
    Curb weight of vehicle, including all liquids and full tank of fuel and full load of cargo and passengers.
   */
   var grossWeight = Field<Int?, NoArguments>("grossWeight")

   /**
    Overall vehicle height, in mm.
   */
   var height = Field<Int?, NoArguments>("height")

   /**
    Overall vehicle length, in mm.
   */
   var length = Field<Int?, NoArguments>("length")

   var parkingBrake = Field<Vehicle_Chassis_ParkingBrake?, NoArguments>("parkingBrake")

   var steeringWheel = Field<Vehicle_Chassis_SteeringWheel?, NoArguments>("steeringWheel")

   /**
    Maximum weight, in kilos, of trailer.
   */
   var towWeight = Field<Int?, NoArguments>("towWeight")

   /**
    Overall wheel tracking, in mm.
   */
   var track = Field<Int?, NoArguments>("track")

   var trailer = Field<Vehicle_Chassis_Trailer?, NoArguments>("trailer")

   /**
    Overall wheel base, in mm.
   */
   var wheelbase = Field<Int?, NoArguments>("wheelbase")

   /**
    Overall vehicle width, in mm.
   */
   var width = Field<Int?, NoArguments>("width")
}
