import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Cabin_Lights_Row1_Left {
     """
     Is passenger light on
     """
     isPassengerOn: Boolean
   }
*/

final class Vehicle_Cabin_Lights_Light: Object, ObjectSchema {

   /**
    Is passenger light on
   */
   var isPassengerOn = Field<Bool?, NoArguments>("isPassengerOn")
}
