import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Cabin_Lights_Row1 {
     """
     Is light shared across first row on
     """
     isSharedOn: Boolean
     left: Vehicle_Cabin_Lights_Row1_Left
     right: Vehicle_Cabin_Lights_Row1_Right
   }
*/

final class Vehicle_Cabin_Lights_Row: Object, ObjectSchema {

   /**
    Is light shared across first row on
   */
   var isSharedOn = Field<Bool?, NoArguments>("isSharedOn")

   var left = Field<Vehicle_Cabin_Lights_Light?, NoArguments>("left")

   var right = Field<Vehicle_Cabin_Lights_Light?, NoArguments>("right")
}
