import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Cabin_Door_Row1_Left {
     """
     Is door child lock engaged. True = Engaged. False = Disengaged.
     """
     isChildLockActive: Boolean
     """
     Is door locked or unlocked. True = Locked. False = Unlocked.
     """
     isLocked: Boolean
     """
     Is door open or closed
     """
     isOpen: Boolean
     shade: Vehicle_Cabin_Door_Row1_Left_Shade
     window: Vehicle_Cabin_Door_Row1_Left_Window
   }
*/

public final class Vehicle_Cabin_Door: Object, ObjectSchema {

   /**
    Is door child lock engaged. True = Engaged. False = Disengaged.
   */
   var isChildLockActive = Field<Bool?, NoArguments>("isChildLockActive")

   /**
    Is door locked or unlocked. True = Locked. False = Unlocked.
   */
   var isLocked = Field<Bool?, NoArguments>("isLocked")

   /**
    Is door open or closed
   */
   var isOpen = Field<Bool?, NoArguments>("isOpen")

   var shade = Field<Vehicle_Cabin_Door_Shade?, NoArguments>("shade")

   var window = Field<Vehicle_Cabin_Door_Window?, NoArguments>("window")


   public init() {

   }
}
