import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   enum Vehicle_Cabin_HVAC_Row1_Left_AirDistribution_Enum {
     up
     middle
     down
   }
*/

enum Vehicle_Cabin_HVAC_AirDistribution_Enum: String, Enum {
   case up = "up"
   case middle = "middle"
   case down = "down"
}
