import Artemis

/*
 This file was generated by Artemis for the following GraphQL object:

   type Vehicle_Cabin_HVAC {
     """
     Ambient air temperature
     """
     ambientAirTemperature: Float
     """
     Is Air conditioning active.
     """
     isAirConditioningActive: Boolean
     """
     Is front defroster active.
     """
     isFrontDefrosterActive: Boolean
     """
     Is rear defroster active.
     """
     isRearDefrosterActive: Boolean
     """
     Is recirculation active.
     """
     isRecirculationActive: Boolean
     row1: Vehicle_Cabin_HVAC_Row1
     row2: Vehicle_Cabin_HVAC_Row2
     row3: Vehicle_Cabin_HVAC_Row3
     row4: Vehicle_Cabin_HVAC_Row4
   }
*/

final class Vehicle_Cabin_HVAC: Object, ObjectSchema {

   /**
    Ambient air temperature
   */
   var ambientAirTemperature = Field<Float?, NoArguments>("ambientAirTemperature")

   /**
    Is Air conditioning active.
   */
   var isAirConditioningActive = Field<Bool?, NoArguments>("isAirConditioningActive")

   /**
    Is front defroster active.
   */
   var isFrontDefrosterActive = Field<Bool?, NoArguments>("isFrontDefrosterActive")

   /**
    Is rear defroster active.
   */
   var isRearDefrosterActive = Field<Bool?, NoArguments>("isRearDefrosterActive")

   /**
    Is recirculation active.
   */
   var isRecirculationActive = Field<Bool?, NoArguments>("isRecirculationActive")

   var row1 = Field<Vehicle_Cabin_HVAC_Row?, NoArguments>("row1")

   var row2 = Field<Vehicle_Cabin_HVAC_Row?, NoArguments>("row2")

   var row3 = Field<Vehicle_Cabin_HVAC_Row?, NoArguments>("row3")

   var row4 = Field<Vehicle_Cabin_HVAC_Row?, NoArguments>("row4")
}
