//
//  ADAS.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 12.05.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class ADAS: Object, ObjectSchema {

    public var abs = Field<ADASABS?, NoArguments>("abs")

    public var cruiseControl = Field<ADASCruiseControl?, NoArguments>("cruiseControl")

    public var esc = Field<ADASESC?, NoArguments>("esc")

    public var laneDepartureDetection = Field<ADASLaneDepartureDetection?, NoArguments>("laneDepartureDetection")

    public var obstacleDetection = Field<ADASObstacleDetection?, NoArguments>("obstacleDetection")

    public var tcs = Field<ADASTCS?, NoArguments>("tcs")

    public required init() { }
}