//
//  BodyTrunk.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class BodyTrunk: Object, ObjectSchema {

    /// Is trunk locked or unlocked. True = Locked. False = Unlocked.
    public var isLocked = Field<Bool?, NoArguments>("isLocked")

    /// Trunk open or closed. True = Open. False = Closed
    public var isOpen = Field<Bool?, NoArguments>("isOpen")

    public required init() { }
}
