//
//  BodyWindshieldRearWipingStatus.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 12.05.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum BodyWindshieldRearWipingStatus: String, Enum {

    case off = "off"

    case slow = "slow"

    case medium = "medium"

    case fast = "fast"

    case interval = "interval"

    case rainsensor = "rainsensor"
}