//
//  BodyWindshield.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 13.05.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class BodyWindshield: Object, ObjectSchema {

    public var front = Field<BodyWindshieldFront?, NoArguments>("front")

    public var rear = Field<BodyWindshieldRear?, NoArguments>("rear")

    public required init() { }
}