//
//  BodyWindshieldFrontWipingStatus.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 13.05.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum BodyWindshieldFrontWipingStatus: String, Enum {

    case off = "off"

    case slow = "slow"

    case medium = "medium"

    case fast = "fast"

    case interval = "interval"

    case rainsensor = "rainsensor"
}