//
//  BodyWindshieldRearWiping.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 12.05.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class BodyWindshieldRearWiping: Object, ObjectSchema {

    /// Rear wiper status
    public var status = Field<BodyWindshieldRearWipingStatus?, NoArguments>("status")

    public required init() { }
}