//
//  BodyRefuelPosition.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 15.05.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum BodyRefuelPosition: String, Enum {

    case frontLeft = "front_left"

    case frontRight = "front_right"

    case middleLeft = "middle_left"

    case middleRight = "middle_right"

    case rearLeft = "rear_left"

    case rearRight = "rear_right"
}