//
//  CabinHVACRow2RightAirDistribution.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 12.05.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum CabinHVACRow2RightAirDistribution: String, Enum {

    case up = "up"

    case middle = "middle"

    case down = "down"
}