//
//  CabinLightsRow2.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class CabinLightsRow2: Object, ObjectSchema {

    /// Is light shared across second row on
    public var isSharedOn = Field<Bool?, NoArguments>("isSharedOn")

    var `left` = Field<CabinLightsRow2Left?, NoArguments>("left")

    var `right` = Field<CabinLightsRow2Right?, NoArguments>("right")

    public required init() { }
}
