//
//  CabinHVACRow3LeftAirDistribution.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 13.05.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum CabinHVACRow3LeftAirDistribution: String, Enum {

    case up = "up"

    case middle = "middle"

    case down = "down"
}