//
//  CabinSeatRow1.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class CabinSeatRow1: Object, ObjectSchema {

    public var pos1 = Field<CabinSeatRow1Pos1?, NoArguments>("pos1")

    public var pos2 = Field<CabinSeatRow1Pos2?, NoArguments>("pos2")

    public var pos3 = Field<CabinSeatRow1Pos3?, NoArguments>("pos3")

    public var pos4 = Field<CabinSeatRow1Pos4?, NoArguments>("pos4")

    public var pos5 = Field<CabinSeatRow1Pos5?, NoArguments>("pos5")

    public required init() { }
}
