//
//  CabinSteeringWheel.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class CabinSteeringWheel: Object, ObjectSchema {

    /// Position of the steering wheel inside the cabin
    public var position = Field<CabinSteeringWheelPosition?, NoArguments>("position")

    public required init() { }
}
