//
//  CabinInfotainment.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 13.05.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class CabinInfotainment: Object, ObjectSchema {

    public var hmi = Field<CabinInfotainmentHMI?, NoArguments>("hmi")

    public var media = Field<CabinInfotainmentMedia?, NoArguments>("media")

    public var navigation = Field<CabinInfotainmentNavigation?, NoArguments>("navigation")

    public required init() { }
}