//
//  CabinInfotainmentHMIDayNightMode.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 13.05.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum CabinInfotainmentHMIDayNightMode: String, Enum {

    case Day = "Day"

    case Night = "Night"
}