//
//  CabinLights.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 12.05.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class CabinLights: Object, ObjectSchema {

    /// How much ambient light is detected in cabin. 0 = No ambient light. 100 = Full brightness
    public var ambientLight = Field<Int?, NoArguments>("ambientLight")

    /// Is central dome light light on
    public var isDomeOn = Field<Bool?, NoArguments>("isDomeOn")

    /// Is glove box light on
    public var isGloveBoxOn = Field<Bool?, NoArguments>("isGloveBoxOn")

    /// Is trunk light light on
    public var isTrunkOn = Field<Bool?, NoArguments>("isTrunkOn")

    /// Intensity of the interior lights. 0 = Off. 100 = Full brightness.
    public var lightIntensity = Field<Int?, NoArguments>("lightIntensity")

    public var row1 = Field<CabinLightsRow1?, NoArguments>("row1")

    public var row2 = Field<CabinLightsRow2?, NoArguments>("row2")

    public var row3 = Field<CabinLightsRow3?, NoArguments>("row3")

    public var row4 = Field<CabinLightsRow4?, NoArguments>("row4")

    public required init() { }
}