//
//  CabinDoorRow2LeftWindowSwitch.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 13.05.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum CabinDoorRow2LeftWindowSwitch: String, Enum {

    case Inactive = "Inactive"

    case Close = "Close"

    case Open = "Open"

    case OneShotClose = "OneShotClose"

    case OneShotOpen = "OneShotOpen"
}