//
//  CabinSteeringWheel.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 12.05.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class CabinSteeringWheel: Object, ObjectSchema {

    /// Position of the steering wheel inside the cabin
    public var position = Field<CabinSteeringWheelPosition?, NoArguments>("position")

    public required init() { }
}