//
//  CabinInfotainmentMediaAction.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 13.05.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum CabinInfotainmentMediaAction: String, Enum {

    case unknown = "unknown"

    case Stop = "Stop"

    case Play = "Play"

    case FastForward = "FastForward"

    case FastBackward = "FastBackward"

    case SkipForward = "SkipForward"

    case SkipBackward = "SkipBackward"
}