//
//  CabinRearviewMirror.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class CabinRearviewMirror: Object, ObjectSchema {

    /// Dimming level of rearview mirror. 0 = undimmed. 100 = fully dimmed
    public var dimmingLevel = Field<Int?, NoArguments>("dimmingLevel")

    public required init() { }
}
