//
//  CabinLightsRow1.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class CabinLightsRow1: Object, ObjectSchema {

    /// Is light shared across first row on
    public var isSharedOn = Field<Bool?, NoArguments>("isSharedOn")

    var `left` = Field<CabinLightsRow1Left?, NoArguments>("left")

    var `right` = Field<CabinLightsRow1Right?, NoArguments>("right")

    public required init() { }
}
