//
//  CabinSunroofSwitch.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum CabinSunroofSwitch: String, Enum {

    case Inactive = "Inactive"

    case Close = "Close"

    case Open = "Open"

    case OneShotClose = "OneShotClose"

    case OneShotOpen = "OneShotOpen"

    case TiltUp = "TiltUp"

    case TiltDown = "TiltDown"
}