//
//  ChassisAxleRow1Wheel.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class ChassisAxleRow1Wheel: Object, ObjectSchema {

    var `left` = Field<ChassisAxleRow1WheelLeft?, NoArguments>("left")

    var `right` = Field<ChassisAxleRow1WheelRight?, NoArguments>("right")

    public required init() { }
}