//
//  ChassisAxle.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 13.05.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class ChassisAxle: Object, ObjectSchema {

    /// Number of axles on the vehicle
    public var count = Field<Int?, NoArguments>("count")

    public var row1 = Field<ChassisAxleRow1?, NoArguments>("row1")

    public var row2 = Field<ChassisAxleRow2?, NoArguments>("row2")

    public required init() { }
}