//
//  ChassisAxleRow2Wheel.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 15.05.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class ChassisAxleRow2Wheel: Object, ObjectSchema {

    public var `left` = Field<ChassisAxleRow2WheelLeft?, NoArguments>("left")

    public var `right` = Field<ChassisAxleRow2WheelRight?, NoArguments>("right")

    public required init() { }
}