//
//  ChassisTrailer.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 13.05.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class ChassisTrailer: Object, ObjectSchema {

    /// Signal indicating if trailer is connected or not.
    public var connected = Field<Bool?, NoArguments>("connected")

    public required init() { }
}