//
//  ChassisAxleRow1Wheel.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 12.05.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class ChassisAxleRow1Wheel: Object, ObjectSchema {

    public var `left` = Field<ChassisAxleRow1WheelLeft?, NoArguments>("left")

    public var `right` = Field<ChassisAxleRow1WheelRight?, NoArguments>("right")

    public required init() { }
}