//
//  DrivetrainTransmissionDriveType.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 12.05.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum DrivetrainTransmissionDriveType: String, Enum {

    case unknown = "unknown"

    case forwardWheelDrive = "forward_wheel_drive"

    case rearWheelDrive = "rear_wheel_drive"

    case allWheelDrive = "all_wheel_drive"
}