//
//  DrivetrainInternalCombustionEngineFuelType.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 12.05.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum DrivetrainInternalCombustionEngineFuelType: String, Enum {

    case unknown = "unknown"

    case gasoline = "gasoline"

    case diesel = "diesel"

    case E85 = "E85"

    case CNG = "CNG"
}