//
//  DrivetrainFuelSystemHybridType.swift
//  HMVssGraphQLClient
//
//  Generated by HMVssGraphQLClient on 16.02.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum DrivetrainFuelSystemHybridType: String, Enum {

    case unknown = "unknown"

    case notApplicable = "not_applicable"

    case stopStart = "stop_start"

    case beltIsg = "belt_ISG"

    case CIMG = "CIMG"

    case PHEV = "PHEV"
}