//
//  DrivetrainTransmissionGearChangeMode.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 12.05.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public enum DrivetrainTransmissionGearChangeMode: String, Enum {

    case manual = "manual"

    case automatic = "automatic"
}