//
//  OBDO2WR.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 13.05.2020.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class OBDO2WR: Object, ObjectSchema {

    public var sensor1 = Field<OBDO2WRSensor1?, NoArguments>("sensor1")

    public var sensor2 = Field<OBDO2WRSensor2?, NoArguments>("sensor2")

    public var sensor3 = Field<OBDO2WRSensor3?, NoArguments>("sensor3")

    public var sensor4 = Field<OBDO2WRSensor4?, NoArguments>("sensor4")

    public var sensor5 = Field<OBDO2WRSensor5?, NoArguments>("sensor5")

    public var sensor6 = Field<OBDO2WRSensor6?, NoArguments>("sensor6")

    public var sensor7 = Field<OBDO2WRSensor7?, NoArguments>("sensor7")

    public var sensor8 = Field<OBDO2WRSensor8?, NoArguments>("sensor8")

    public required init() { }
}