//
//  OBDO2AltBank2Sensor2.swift
//  VSSGraphQL
//
//  Generated by VSSGraphQL on 12.05.20.
//  Copyright © 2020 High Mobility GmbH. All rights reserved.
//

import Artemis
import Foundation


public class OBDO2AltBank2Sensor2: Object, ObjectSchema {

    /// Dummy description
    public var dummyField = Field<String?, NoArguments>("dummyField")

    public required init() { }
}